package com.example.rms;
import com.example.rms.user.application.*;
import com.example.rms.user.application.contract.UserAccessService;
import com.example.rms.requirement.application.*;
import com.example.rms.requirement.application.contract.RequirementMutationService;
import com.example.rms.review.application.*;
import com.example.rms.relation.application.*;
import com.example.rms.relation.application.port.RelationStore;
import com.example.rms.shared.application.*;
import com.example.rms.shared.infrastructure.*;
import com.example.rms.audit.application.contract.FailureAuditService;
import com.zaxxer.hikari.HikariDataSource;
import java.sql.*;
import java.nio.file.*;
import org.springframework.orm.jpa.JpaTransactionManager;
import org.springframework.beans.factory.annotation.Qualifier;
import com.example.rms.version.application.contract.VersionAppendService;
import com.example.rms.shared.application.Actor;
import com.example.rms.shared.domain.*;
import com.fasterxml.jackson.databind.*;
import jakarta.persistence.EntityManager;
import java.util.*;
import java.util.concurrent.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.autoconfigure.web.servlet.*;
import org.springframework.mock.web.MockHttpSession;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.test.web.servlet.*;
import org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
import static org.junit.jupiter.api.Assertions.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
/** Developer-owned synthetic probes; retained real MySQL, no acceptance/oracle inputs. */
@SpringBootTest @AutoConfigureMockMvc(print=MockMvcPrint.NONE)
class Wave4DeveloperIntegrationTest {
    @Autowired MockMvc mvc;@Autowired ObjectMapper json;@Autowired EntityManager em;@Autowired UserAdministrationService administration;@Autowired UserAccessService access;@Autowired RequirementService requirements;@Autowired ReviewService reviews;@Autowired RelationTransactions writes;@Autowired RelationService relations;@Autowired RelationStore relationStore;@Autowired RequirementTransactions requirementWrites;@Autowired MySqlGraphWriteExecutor graph;@Autowired PinnedDataSource pinned;@Autowired @Qualifier("rmsGraphPool") HikariDataSource pool;@Autowired CurrentActor current;@Autowired FailureAuditService failures;@Autowired PlatformTransactionManager manager;@Autowired VersionAppendService versions;@Autowired RequirementMutationService mutations;
    private static final String PASSWORD="Wave four developer é";
    private record Created(String username,UserData user) {}
    @AfterEach void cleanupContext() { org.springframework.security.test.context.TestSecurityContextHolder.clearContext(); }
    private long adminId() { return ((Number)em.createNativeQuery("SELECT MIN(u.userId) FROM `User` u JOIN `UserRole` ur ON ur.userId=u.userId JOIN `Role` r ON r.roleId=ur.roleId WHERE u.accountStatus='ENABLED' AND r.roleCode='ADMIN'").getSingleResult()).longValue(); }
    private void act(long id) { Actor actor=access.requireEnabledActor(id);SecurityContextHolder.getContext().setAuthentication(UsernamePasswordAuthenticationToken.authenticated(actor,null,List.of())); }
    private Created user(String... roles) { act(adminId());String name="w4_"+UUID.randomUUID().toString().replace("-","");var result=new Created(name,administration.create(name,name+"@example.invalid","Wave four synthetic",PASSWORD,List.of(roles)));org.springframework.security.test.context.TestSecurityContextHolder.clearContext();return result; }
    private MockHttpSession login(Created u)throws Exception { org.springframework.security.test.context.TestSecurityContextHolder.clearContext();var csrf=mvc.perform(get("/api/v1/auth/csrf")).andExpect(status().isOk()).andReturn();var session=(MockHttpSession)csrf.getRequest().getSession(false);mvc.perform(post("/api/v1/auth/login").session(session).header("X-CSRF-TOKEN",read(csrf).get("token").asText()).contentType("application/json").content(json.writeValueAsString(Map.of("login",u.username(),"password",PASSWORD)))).andExpect(status().isOk());return session; }
    private JsonNode read(MvcResult r)throws Exception { return json.readTree(r.getResponse().getContentAsString()); }
    private JsonNode postJson(String path,MockHttpSession s,Object body,int expected)throws Exception { org.springframework.security.test.context.TestSecurityContextHolder.clearContext();String csrf=read(mvc.perform(get("/api/v1/auth/csrf").session(s)).andExpect(status().isOk()).andReturn()).get("token").asText();return read(mvc.perform(post(path).session(s).header("X-CSRF-TOKEN",csrf).contentType("application/json").content(json.writeValueAsString(body))).andExpect(status().is(expected)).andReturn()); }
    private JsonNode patch(String path,MockHttpSession s,Object body,int expected)throws Exception { org.springframework.security.test.context.TestSecurityContextHolder.clearContext();String csrf=read(mvc.perform(get("/api/v1/auth/csrf").session(s)).andExpect(status().isOk()).andReturn()).get("token").asText();return read(mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.patch(path).session(s).header("X-CSRF-TOKEN",csrf).contentType("application/json").content(json.writeValueAsString(body))).andExpect(status().is(expected)).andReturn()); }
    private JsonNode getJson(String path,MockHttpSession s,int expected)throws Exception { org.springframework.security.test.context.TestSecurityContextHolder.clearContext();return read(mvc.perform(get(path).session(s)).andExpect(status().is(expected)).andReturn()); }
    private Map<String,Object> content(String title) { return Map.of("title",title,"description","Explicit observable behavior","level","USER","kind","FUNCTIONAL","priority","HIGH","source","Synthetic stakeholder interview","rationale","Prevent data loss","acceptanceCriteria","Given a valid form, saving returns its saved record with unchanged values."); }
    private JsonNode create(MockHttpSession s)throws Exception { return postJson("/api/v1/requirements",s,content("w4_"+UUID.randomUUID()),201); }
    private String path(JsonNode r) { return "/api/v1/requirements/"+r.get("requirementId").asText(); }
    private JsonNode submit(JsonNode r,MockHttpSession s)throws Exception { return postJson(path(r)+"/submit",s,Map.of("expectedLockVersion",r.get("lockVersion").asText()),201); }
    private JsonNode decision(JsonNode review,MockHttpSession s,String value,String revision,String comment,int expected)throws Exception { Map<String,Object> body=new HashMap<>();body.put("decision",value);body.put("expectedRequirementLockVersion",revision);body.put("comment",comment);return postJson("/api/v1/requirement-reviews/"+review.get("reviewId").asText()+"/decision",s,body,expected); }
    private long count(String table,String where,long id) { return ((Number)em.createNativeQuery("SELECT COUNT(*) FROM `"+table+"` WHERE "+where+"=:id").setParameter("id",id).getSingleResult()).longValue(); }
    private long auditCount(String target,String action,String outcome) { return ((Number)em.createNativeQuery("SELECT COUNT(*) FROM `AuditEvent` WHERE targetId=:id AND action=:action AND outcome=:outcome").setParameter("id",target).setParameter("action",action).setParameter("outcome",outcome).getSingleResult()).longValue(); }

    private static final List<Map<String,Object>> GRAPH_EVIDENCE=new ArrayList<>();
    private static final ObjectMapper EVIDENCE_JSON=new ObjectMapper();
    private static synchronized void record(String name,Map<String,Object> values)throws Exception { var row=new LinkedHashMap<String,Object>();row.put("id",name);row.put("status","PASS");row.putAll(values);GRAPH_EVIDENCE.add(row);EVIDENCE_JSON.writerWithDefaultPrettyPrinter().writeValue(Path.of("target/wave4-graph-developer-results.json").toFile(),Map.of("phase","G3-B","wave",4,"kind","DEVELOPER_REAL_MYSQL_PROBES","tests",GRAPH_EVIDENCE));System.out.println("WAVE4_GRAPH_DEVELOPER_EVIDENCE "+EVIDENCE_JSON.writeValueAsString(row)); }
    private Connection independent()throws SQLException { return DriverManager.getConnection(System.getenv("RMS_DB_URL"),System.getenv("RMS_DB_USERNAME"),System.getenv("RMS_DB_PASSWORD")); }
    private static Number scalar(Connection c,String sql,Object...args)throws SQLException { return MySqlGraphWriteExecutor.query(c,sql,args); }
    private void noOwner()throws SQLException { try(var c=independent()){assertNull(scalar(c,"SELECT IS_USED_LOCK(?)",MySqlGraphWriteExecutor.LOCK_NAME));} }
    private static int index(GraphTrace t,String event){var rows=t.events();for(int i=0;i<rows.size();i++)if(event.equals(rows.get(i).get("name")))return i;return -1;}
    private static void ordered(GraphTrace t,String...events){int previous=-1;for(String event:events){int value=index(t,event);assertTrue(value>previous,"Missing or misordered graph event "+event);previous=value;}}
    private JsonNode relation(JsonNode s,JsonNode t,String type,MockHttpSession session,int expected)throws Exception { return postJson("/api/v1/relations",session,Map.of("sourceRequirementId",s.get("requirementId").asText(),"targetRequirementId",t.get("requirementId").asText(),"relationType",type,"description","Synthetic relation description","expectedSourceLockVersion",s.get("lockVersion").asText(),"expectedTargetLockVersion",t.get("lockVersion").asText()),expected); }
    private void remove(JsonNode edge,JsonNode source,JsonNode target,MockHttpSession session,int expected)throws Exception { org.springframework.security.test.context.TestSecurityContextHolder.clearContext();String csrf=read(mvc.perform(get("/api/v1/auth/csrf").session(session)).andExpect(status().isOk()).andReturn()).get("token").asText();mvc.perform(delete("/api/v1/relations/"+edge.get("relationId").asText()).queryParam("expectedSourceLockVersion",source.get("lockVersion").asText()).queryParam("expectedTargetLockVersion",target.get("lockVersion").asText()).session(session).header("X-CSRF-TOKEN",csrf)).andExpect(status().is(expected)); }
    @Test void allSixTypesNormalizationOriginalRevisionMappingAndDeleteAudit()throws Exception {
        MockHttpSession eng=login(user("REQUIREMENT_ENGINEER")),viewer=login(user("VIEWER"));var low=create(eng);var high=create(eng);high=patch(path(high)+"/content",eng,Map.of("title","High revised once","expectedLockVersion","0"),200);assertEquals("1",high.get("lockVersion").asText());assertEquals("INVALID_INPUT",relation(low,low,"DEPENDS_ON",eng,400).get("code").asText());
        var edges=new ArrayList<JsonNode>();for(String type:List.of("DEPENDS_ON","REFINES","DERIVED_FROM","CONFLICTS_WITH","DUPLICATES","RELATES_TO")){var e=relation(high,low,type,eng,201);edges.add(e);assertTrue(e.get("relationId").isTextual());boolean symmetric=List.of("CONFLICTS_WITH","DUPLICATES","RELATES_TO").contains(type);assertEquals((symmetric?low:high).get("requirementId"),e.get("sourceRequirementId"));assertEquals((symmetric?high:low).get("requirementId"),e.get("targetRequirementId"));relation(high,low,type,eng,409);if(symmetric)assertEquals("DUPLICATE",relation(low,high,type,eng,409).get("code").asText());}
        var swapped=new HashMap<String,Object>();swapped.put("sourceRequirementId",high.get("requirementId").asText());swapped.put("targetRequirementId",low.get("requirementId").asText());swapped.put("relationType","RELATES_TO");swapped.put("expectedSourceLockVersion","0");swapped.put("expectedTargetLockVersion","1");assertEquals("LOCK_VERSION_CONFLICT",postJson("/api/v1/relations",eng,swapped,409).get("code").asText());
        var page=getJson(path(low)+"/relations?size=2&page=1",viewer,200);assertEquals(6,page.get("totalElements").asInt());assertTrue(page.get("totalElements").isIntegralNumber());assertEquals(2,page.get("items").size());assertEquals(low,getJson(path(low),viewer,200));assertEquals(high,getJson(path(high),viewer,200));getJson(path(low)+"/relations?size=101",viewer,400);relation(high,low,"UNKNOWN",eng,400);relation(high,low,"REFINES",viewer,403);
        remove(edges.get(0),high,low,viewer,403);org.springframework.security.test.context.TestSecurityContextHolder.clearContext();String csrf=read(mvc.perform(get("/api/v1/auth/csrf").session(eng)).andReturn()).get("token").asText();mvc.perform(delete("/api/v1/relations/"+edges.get(0).get("relationId").asText()).session(eng).header("X-CSRF-TOKEN",csrf)).andExpect(status().isBadRequest());
        for(JsonNode e:edges){boolean normal=e.get("sourceRequirementId").equals(low.get("requirementId"));remove(e,normal?low:high,normal?high:low,eng,204);assertEquals(1,auditCount(e.get("relationId").asText(),"RELATION_REMOVE","SUCCESS"));JsonNode before=json.readTree((String)em.createNativeQuery("SELECT CAST(beforeData AS CHAR) FROM `AuditEvent` WHERE targetType='RELATION' AND targetId=:id AND action='RELATION_REMOVE' AND outcome='SUCCESS'").setParameter("id",e.get("relationId").asText()).getSingleResult());assertEquals(e.get("sourceRequirementId"),before.get("sourceRequirementId"));assertEquals(e.get("relationType"),before.get("relationType"));remove(e,normal?low:high,normal?high:low,eng,404);}
        assertEquals(0,getJson(path(low)+"/relations",viewer,200).get("items").size());assertEquals(low,getJson(path(low),eng,200));assertEquals(high,getJson(path(high),eng,200));noOwner();
    }
    @Test void finiteCurrentTracePreservesDirectionTypesVisitedAndStrictDto()throws Exception {
        MockHttpSession eng=login(user("REQUIREMENT_ENGINEER")),viewer=login(user("VIEWER"));var a=create(eng);var b=create(eng);var c=create(eng);var ab=relation(a,b,"DEPENDS_ON",eng,201);var bc=relation(b,c,"DEPENDS_ON",eng,201);relation(c,a,"RELATES_TO",eng,201);relation(b,a,"REFINES",eng,201);assertEquals("DEPENDENCY_CYCLE",relation(c,a,"DEPENDS_ON",eng,409).get("code").asText());
        var d1=getJson(path(a)+"/trace?depth=1&relationType=DEPENDS_ON",viewer,200);assertEquals(2,d1.get("nodes").size());assertEquals(1,d1.get("edges").size());assertTrue(d1.get("truncated").asBoolean());assertTrue(d1.get("depth").isIntegralNumber());assertTrue(d1.get("rootRequirementId").isTextual());assertEquals(ab,d1.get("edges").get(0));
        var d2=getJson(path(a)+"/trace?depth=2&relationType=DEPENDS_ON",viewer,200);assertEquals(3,d2.get("nodes").size());assertEquals(2,d2.get("edges").size());assertFalse(d2.get("truncated").asBoolean());assertEquals(bc,d2.get("edges").get(1));var complete=getJson(path(a)+"/trace?depth=10",viewer,200);assertEquals(3,complete.get("nodes").size());assertEquals(4,complete.get("edges").size());assertFalse(complete.get("truncated").asBoolean());var ids=new HashSet<String>();for(var n:complete.get("nodes"))assertTrue(ids.add(n.get("requirementId").asText()));getJson(path(a)+"/trace?depth=0",viewer,400);getJson(path(a)+"/trace?depth=11",viewer,400);getJson(path(a)+"/trace?relationType=UNKNOWN",viewer,400);getJson("/api/v1/requirements/9223372036854775807/trace",viewer,404);
        postJson("/api/v1/relations",eng,Map.of("sourceRequirementId",a.get("requirementId").asInt(),"targetRequirementId",b.get("requirementId").asText(),"relationType","REFINES","expectedSourceLockVersion","0","expectedTargetLockVersion","0"),400);postJson("/api/v1/relations",eng,Map.of("sourceRequirementId",a.get("requirementId").asText(),"targetRequirementId",b.get("requirementId").asText(),"relationType","REFINES","expectedSourceLockVersion","0","expectedTargetLockVersion","0","createdBy","1"),400);assertEquals(a,getJson(path(a),viewer,200));assertEquals(0,getJson(path(a)+"/versions",viewer,200).get("items").size());noOwner();
    }
    @Test void withdrawIsLogicalNeverSubmittedUnrelatedDraftAndPreservesReadonlyHistory()throws Exception {
        Created engineer=user("REQUIREMENT_ENGINEER");MockHttpSession eng=login(engineer),rev=login(user("REVIEWER")),viewer=login(user("VIEWER"));var a=create(eng);var b=create(eng);var edge=relation(a,b,"RELATES_TO",eng,201);assertEquals("STATE_CONFLICT",postJson(path(a)+"/withdraw",eng,Map.of("expectedLockVersion","0"),409).get("code").asText());remove(edge,a,b,eng,204);postJson(path(a)+"/withdraw",viewer,Map.of("expectedLockVersion","0"),403);postJson(path(a)+"/withdraw",eng,Map.of("expectedLockVersion","0","withdrawnBy","1"),400);var withdrawn=postJson(path(a)+"/withdraw",eng,Map.of("expectedLockVersion","0"),200);assertEquals(1,withdrawn.get("isWithdrawn").asInt());assertEquals("DRAFT",withdrawn.get("status").asText());assertEquals("1",withdrawn.get("lockVersion").asText());assertEquals(Long.toString(engineer.user().userId()),withdrawn.get("withdrawnBy").asText());assertFalse(withdrawn.get("withdrawnAt").isNull());assertEquals(a.get("title"),withdrawn.get("title"));assertEquals(withdrawn,getJson(path(a),viewer,200));var listing=getJson("/api/v1/requirements?keyword="+a.get("title").asText(),viewer,200);assertEquals(0,listing.get("items").size());assertEquals(0,getJson(path(a)+"/reviews",viewer,200).get("items").size());assertEquals(0,getJson(path(a)+"/relations",viewer,200).get("items").size());postJson(path(a)+"/withdraw",eng,Map.of("expectedLockVersion","1"),409);patch(path(a)+"/content",eng,Map.of("title","No edit","expectedLockVersion","1"),409);postJson(path(a)+"/comments",eng,Map.of("content","No new comment"),409);relation(withdrawn,b,"DEPENDS_ON",eng,409);
        var returned=create(eng);var round=submit(returned,eng);decision(round,rev,"REQUEST_CHANGES","1","Improve observable behavior",200);var draft=getJson(path(returned),eng,200);assertEquals("DRAFT",draft.get("status").asText());assertFalse(draft.get("firstSubmittedAt").isNull());postJson(path(draft)+"/withdraw",eng,Map.of("expectedLockVersion","2"),409);var rejected=create(eng);round=submit(rejected,eng);decision(round,rev,"REJECT","1","Synthetic rejected proposal",200);var reopened=postJson(path(rejected)+"/reopen",eng,Map.of("expectedLockVersion","2"),200);postJson(path(reopened)+"/withdraw",eng,Map.of("expectedLockVersion","3"),409);noOwner();
    }
    private RequirementData fixture(long actor){act(actor);return requirements.create("w4 "+UUID.randomUUID(),"Observable synthetic behavior","USER","FUNCTIONAL","HIGH","source","rationale","Saving displays the saved record").requirement();}
    @Test void productionExecutorSameConnectionHeldThroughCommitCompetingTimeoutAndRelease()throws Exception {
        Created engineer=user("REQUIREMENT_ENGINEER");var a=fixture(engineer.user().userId());var b=fixture(engineer.user().userId());Actor actor=access.requireEnabledActor(engineer.user().userId());var trace=new GraphTrace();var uncommitted=new CountDownLatch(1);var allowCommit=new CountDownLatch(1);var data=new LinkedHashMap<String,Object>();Future<RelationData> future;
        try(var workers=Executors.newSingleThreadExecutor()){future=workers.submit(()->graph.execute(trace,()->{var edge=writes.create(actor,a.requirementId(),b.requirementId(),"DEPENDS_ON",null,"0","0");uncommitted.countDown();assertTrue(allowCommit.await(10,TimeUnit.SECONDS));return edge;}));try{assertTrue(uncommitted.await(10,TimeUnit.SECONDS));try(var independent=independent()){long id=scalar(independent,"SELECT CONNECTION_ID()").longValue();assertNotEquals(trace.graphConnectionId,id);data.put("competingConnectionId",id);data.put("lockOwnerBeforeCommit",scalar(independent,"SELECT IS_USED_LOCK(?)",MySqlGraphWriteExecutor.LOCK_NAME));long started=System.nanoTime();var value=scalar(independent,"SELECT GET_LOCK(?,1)",MySqlGraphWriteExecutor.LOCK_NAME);long elapsed=TimeUnit.NANOSECONDS.toMillis(System.nanoTime()-started);assertEquals(0,value.intValue());assertTrue(elapsed>=900);data.put("competingGetLockBeforeCommit",value.intValue());data.put("competingElapsedMs",elapsed);assertEquals(0,scalar(independent,"SELECT COUNT(*) FROM `RequirementRelation` WHERE sourceRequirementId=? AND targetRequirementId=?",a.requirementId(),b.requirementId()).intValue());}}finally{allowCommit.countDown();}var edge=future.get(15,TimeUnit.SECONDS);assertEquals(1,auditCount(Long.toString(edge.relationId()),"RELATION_CREATE","SUCCESS"));}
        assertEquals(trace.graphConnectionId,trace.jpaConnectionId);ordered(trace,"PHYSICAL_CONNECTION_PINNED","LOCK_ACQUIRED","TRANSACTION_CALLBACK_ENTERED","COMMIT_COMPLETED","SPRING_TRANSACTION_COMPLETION_AND_CLEANUP_RETURNED","RELEASE_LOCK_COMPLETED","POOL_RETURNED");try(var other=independent()){var value=scalar(other,"SELECT GET_LOCK(?,1)",MySqlGraphWriteExecutor.LOCK_NAME);assertEquals(1,value.intValue());data.put("competingGetLockAfterCommit",value.intValue());scalar(other,"SELECT RELEASE_LOCK(?)",MySqlGraphWriteExecutor.LOCK_NAME);}noOwner();data.put("productionExecution",trace.evidence());record("PRODUCTION_CONNECTION_COMMIT_RELEASE",data);
    }
    @Test void productionRollbackCleanupFaultEvictsWithoutFalseFailedAuditOrReplay()throws Exception {
        Created engineer=user("REQUIREMENT_ENGINEER");var a=fixture(engineer.user().userId());var b=fixture(engineer.user().userId());Actor actor=access.requireEnabledActor(engineer.user().userId());var rollback=new GraphTrace();long successes=((Number)em.createNativeQuery("SELECT COUNT(*) FROM `AuditEvent` WHERE action='RELATION_CREATE' AND outcome='SUCCESS'").getSingleResult()).longValue();assertThrows(MySqlGraphWriteExecutor.GraphWorkException.class,()->graph.execute(rollback,()->{writes.create(actor,a.requirementId(),b.requirementId(),"DEPENDS_ON",null,"0","0");throw new Exception("WAVE4_CHECKED_EXCEPTION_AFTER_WRITES");}));assertEquals(0,count("RequirementRelation","sourceRequirementId",a.requirementId()));assertEquals(successes,((Number)em.createNativeQuery("SELECT COUNT(*) FROM `AuditEvent` WHERE action='RELATION_CREATE' AND outcome='SUCCESS'").getSingleResult()).longValue());ordered(rollback,"ROLLBACK_COMPLETED","RELEASE_LOCK_COMPLETED","POOL_RETURNED");noOwner();
        assertThrows(org.springframework.transaction.IllegalTransactionStateException.class,()->writes.create(actor,a.requirementId(),b.requirementId(),"DEPENDS_ON",null,"0","0"));assertThrows(IllegalStateException.class,()->new TransactionTemplate(manager).executeWithoutResult(status->graph.execute(()->null)));
        var faultTrace=new GraphTrace();var bad=new MySqlGraphWriteExecutor(pool,pinned,(JpaTransactionManager)manager,em,c->scalar(c,"SELECT RMS_WAVE4_RELEASE_FAULT()"));GraphWriteExecutor observed=new GraphWriteExecutor(){public <T>T execute(Work<T> work){return bad.execute(faultTrace,work);}public void requireActive(){bad.requireActive();}};var facade=new RelationService(relationStore,writes,mutations,observed,current,failures);long failed=auditCount("NEW","RELATION_CREATE","FAILED");act(actor.userId());var failure=assertThrows(GraphOutcomeException.class,()->facade.create(Long.toString(a.requirementId()),Long.toString(b.requirementId()),"DEPENDS_ON",null,"0","0"));assertTrue(failure.committed());assertEquals(1,count("RequirementRelation","sourceRequirementId",a.requirementId()));assertEquals(successes+1,((Number)em.createNativeQuery("SELECT COUNT(*) FROM `AuditEvent` WHERE action='RELATION_CREATE' AND outcome='SUCCESS'").getSingleResult()).longValue());assertEquals(failed,auditCount("NEW","RELATION_CREATE","FAILED"));assertTrue(faultTrace.evicted);assertFalse(pinned.isPinned());assertEquals(-1,index(faultTrace,"POOL_RETURNED"));ordered(faultTrace,"COMMIT_COMPLETED","RELEASE_LOCK_FAILURE","CONNECTION_EVICTED_FROM_POOL","PHYSICAL_CONNECTION_ABORTED","EVICTED_HANDLE_CLOSED_NOT_NORMAL_POOL_RETURN");noOwner();var borrowed=new ArrayList<Long>();for(int i=0;i<4;i++)try(var c=pool.getConnection()){long id=scalar(c,"SELECT CONNECTION_ID()").longValue();assertNotEquals(faultTrace.graphConnectionId,id);borrowed.add(id);}var data=new LinkedHashMap<String,Object>();data.put("rollback",rollback.evidence());data.put("releaseFaultAfterCommit",faultTrace.evidence());data.put("borrowedConnectionIdsAfterEviction",borrowed);data.put("falseFailedAuditAdded",false);data.put("businessReplayed",false);data.put("isUsedLock",null);record("PRODUCTION_ROLLBACK_RELEASE_FAULT",data);
    }
    @Test void productionCompetingReverseDependenciesExactlyOneSuccessAndOneCycle()throws Exception {
        Created engineer=user("REQUIREMENT_ENGINEER");var a=fixture(engineer.user().userId());var b=fixture(engineer.user().userId());Actor actor=access.requireEnabledActor(engineer.user().userId());var traces=List.of(new GraphTrace(),new GraphTrace());var ready=new CountDownLatch(2);var start=new CountDownLatch(1);List<String> results=new ArrayList<>();try(var workers=Executors.newFixedThreadPool(2)){List<Future<String>> futures=new ArrayList<>();for(int i=0;i<2;i++){int index=i;futures.add(workers.submit(()->{ready.countDown();assertTrue(start.await(10,TimeUnit.SECONDS));try{graph.execute(traces.get(index),()->writes.create(actor,index==0?a.requirementId():b.requirementId(),index==0?b.requirementId():a.requirementId(),"DEPENDS_ON",null,"0","0"));return "SUCCESS";}catch(RmsException e){return e.code().name();}}));}assertTrue(ready.await(10,TimeUnit.SECONDS));start.countDown();for(var f:futures)results.add(f.get(20,TimeUnit.SECONDS));}assertEquals(1,Collections.frequency(results,"SUCCESS"));assertEquals(1,Collections.frequency(results,"DEPENDENCY_CYCLE"));assertEquals(1,count("RequirementRelation","sourceRequirementId",a.requirementId())+count("RequirementRelation","sourceRequirementId",b.requirementId()));for(var t:traces){assertEquals(t.graphConnectionId,t.jpaConnectionId);ordered(t,"LOCK_ACQUIRED","TRANSACTION_CALLBACK_ENTERED","RELEASE_LOCK_COMPLETED","POOL_RETURNED");}noOwner();record("PRODUCTION_COMPETING_CYCLE",Map.of("outcomes",results,"threads",traces.stream().map(GraphTrace::evidence).toList(),"finalEdgeCount",1));
    }
    @Test void productionWithdrawVersusRelationCreateHasOneWinnerAndAtomicFinalInvariant()throws Exception {
        Created engineer=user("REQUIREMENT_ENGINEER");var a=fixture(engineer.user().userId());var b=fixture(engineer.user().userId());Actor actor=access.requireEnabledActor(engineer.user().userId());var traces=List.of(new GraphTrace(),new GraphTrace());var barrier=new CyclicBarrier(2);List<String> results=new ArrayList<>();try(var workers=Executors.newFixedThreadPool(2)){var withdraw=workers.submit(()->{barrier.await(10,TimeUnit.SECONDS);try{graph.execute(traces.get(0),()->requirementWrites.withdraw(actor,a.requirementId(),"0"));return "SUCCESS";}catch(RmsException e){return e.code().name();}});var create=workers.submit(()->{barrier.await(10,TimeUnit.SECONDS);try{graph.execute(traces.get(1),()->writes.create(actor,a.requirementId(),b.requirementId(),"RELATES_TO",null,"0","0"));return "SUCCESS";}catch(RmsException e){return e.code().name();}});results.add(withdraw.get(20,TimeUnit.SECONDS));results.add(create.get(20,TimeUnit.SECONDS));}assertEquals(1,Collections.frequency(results,"SUCCESS"));assertEquals(1,Collections.frequency(results,"STATE_CONFLICT"));act(actor.userId());var finalParent=requirements.read(Long.toString(a.requirementId())).requirement();long edgeCount=count("RequirementRelation","sourceRequirementId",a.requirementId())+count("RequirementRelation","targetRequirementId",a.requirementId());assertTrue((finalParent.isWithdrawn()==1 && edgeCount==0) || (finalParent.isWithdrawn()==0 && edgeCount==1));noOwner();record("PRODUCTION_WITHDRAW_CREATE_COMPETITION",Map.of("outcomes",results,"isWithdrawn",finalParent.isWithdrawn(),"activeEdgeCount",edgeCount,"threads",traces.stream().map(GraphTrace::evidence).toList()));
    }
}
