package com.example.rms;
import com.example.rms.user.application.*;
import com.example.rms.user.application.contract.UserAccessService;
import com.example.rms.requirement.application.*;
import com.example.rms.comment.application.*;
import com.example.rms.shared.application.Actor;
import com.example.rms.shared.domain.*;
import com.fasterxml.jackson.databind.*;
import jakarta.persistence.EntityManager;
import java.util.*;
import java.util.concurrent.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.autoconfigure.web.servlet.*;
import org.springframework.mock.web.MockHttpSession;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.test.web.servlet.*;
import org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
import static org.junit.jupiter.api.Assertions.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
/** Developer-owned Wave 1 probes against retained MySQL, with synthetic unique data. No G4 oracle inputs. */
@SpringBootTest @AutoConfigureMockMvc(print=MockMvcPrint.NONE)
class Wave1DeveloperIntegrationTest {
    @Autowired MockMvc mvc;@Autowired ObjectMapper json;@Autowired EntityManager em;@Autowired UserAdministrationService administration;@Autowired UserAccessService access;@Autowired RequirementService requirements;@Autowired RequirementTransactions transactions;@Autowired PlatformTransactionManager manager;
    @Autowired CommentService comments;@Autowired CommentTransactions commentTransactions;
    private static final String PASSWORD="  developer pass é  ";
    private record Created(String username,String email,UserData user) {}
    @AfterEach void cleanupContext() { org.springframework.security.test.context.TestSecurityContextHolder.clearContext(); }
    private long adminId() { return ((Number)em.createNativeQuery("SELECT MIN(u.userId) FROM `User` u JOIN `UserRole` ur ON ur.userId=u.userId JOIN `Role` r ON r.roleId=ur.roleId WHERE u.accountStatus='ENABLED' AND r.roleCode='ADMIN'").getSingleResult()).longValue(); }
    private void act(long id) { Actor actor=access.requireEnabledActor(id);SecurityContextHolder.getContext().setAuthentication(UsernamePasswordAuthenticationToken.authenticated(actor,null,List.of())); }
    private Created newUser(String... roles) { act(adminId());String name="w1_"+UUID.randomUUID().toString().replace("-","");String email=name+"@example.invalid";Created user=new Created(name,email,administration.create(name,email,"Developer synthetic",PASSWORD,List.of(roles)));org.springframework.security.test.context.TestSecurityContextHolder.clearContext();return user; }
    private MockHttpSession login(String name,String password)throws Exception { org.springframework.security.test.context.TestSecurityContextHolder.clearContext();var csrf=mvc.perform(get("/api/v1/auth/csrf")).andExpect(status().isOk()).andReturn();var session=(MockHttpSession)csrf.getRequest().getSession(false);String token=read(csrf).get("token").asText();mvc.perform(post("/api/v1/auth/login").session(session).header("X-CSRF-TOKEN",token).contentType("application/json").content(json.writeValueAsString(Map.of("login",name,"password",password)))).andExpect(status().isOk());return session; }
    private MockHttpSession adminSession()throws Exception { return login(System.getenv("RMS_BOOTSTRAP_USERNAME"),System.getenv("RMS_BOOTSTRAP_PASSWORD")); }
    private JsonNode read(MvcResult result)throws Exception { String body=result.getResponse().getContentAsString();return body.isEmpty()?json.nullNode():json.readTree(body); }
    private JsonNode write(String method,String path,MockHttpSession session,Object body,int expected)throws Exception { org.springframework.security.test.context.TestSecurityContextHolder.clearContext();String token=read(mvc.perform(get("/api/v1/auth/csrf").session(session)).andExpect(status().isOk()).andReturn()).get("token").asText();MockHttpServletRequestBuilder builder=switch(method){case "POST"->post(path);case "PATCH"->patch(path);case "PUT"->put(path);case "DELETE"->delete(path);default->throw new IllegalArgumentException();};builder.session(session).header("X-CSRF-TOKEN",token);if(body!=null)builder.contentType("application/json").content(json.writeValueAsString(body));return read(mvc.perform(builder).andExpect(status().is(expected)).andReturn()); }
    private JsonNode getJson(String path,MockHttpSession session,int expected)throws Exception { org.springframework.security.test.context.TestSecurityContextHolder.clearContext();return read(mvc.perform(get(path).session(session)).andExpect(status().is(expected)).andReturn()); }
    private Map<String,Object> draft(String title) { return Map.of("title",title,"description","draft body","level","USER","kind","FUNCTIONAL","priority","HIGH"); }
    private long count(String table) { return ((Number)em.createNativeQuery("SELECT COUNT(*) FROM `"+table+"`").getSingleResult()).longValue(); }
    @Test void adminUserLifecycleProvenanceOriginalPasswordAndOptimisticRevision()throws Exception {
        MockHttpSession admin=adminSession();String name="w1_http_"+UUID.randomUUID().toString().replace("-","");String email=name+"@example.invalid";long before=count("User");
        JsonNode user=write("POST","/api/v1/users",admin,Map.of("username",name,"email",email,"displayName","HTTP synthetic","initialPassword",PASSWORD,"roles",List.of("REQUIREMENT_ENGINEER","VIEWER")),201);String id=user.get("userId").asText();assertTrue(user.get("userId").isTextual());assertTrue(user.get("lockVersion").isTextual());assertFalse(user.has("passwordHash"));assertFalse(user.toString().contains(PASSWORD));assertEquals(Long.toString(adminId()),user.get("assignments").get(0).get("grantedBy").asText());assertEquals(before+1,count("User"));
        JsonNode page=getJson("/api/v1/users?size=1",admin,200);assertTrue(page.get("totalElements").isIntegralNumber());assertEquals(1,page.get("items").size());
        user=write("PATCH","/api/v1/users/"+id,admin,Map.of("displayName","Updated safe name","expectedLockVersion","0"),200);assertEquals("1",user.get("lockVersion").asText());assertEquals(name,user.get("username").asText());login(email,PASSWORD);
        assertEquals("INVALID_INPUT",write("PUT","/api/v1/users/"+id+"/roles",admin,Map.of("roles",List.of(),"expectedLockVersion","1"),400).get("code").asText());
        write("PUT","/api/v1/users/"+id+"/roles",admin,Map.of("roles",List.of("VIEWER","VIEWER"),"expectedLockVersion","1"),400);
        user=write("PUT","/api/v1/users/"+id+"/roles",admin,Map.of("roles",List.of("REVIEWER","PROJECT_MEMBER"),"expectedLockVersion","1"),200);assertEquals("2",user.get("lockVersion").asText());assertEquals(2,user.get("assignments").size());
        user=write("POST","/api/v1/users/"+id+"/disable",admin,Map.of("expectedLockVersion","2"),200);assertEquals("DISABLED",user.get("accountStatus").asText());
        user=write("PUT","/api/v1/users/"+id+"/roles",admin,Map.of("roles",List.of(),"expectedLockVersion","3"),200);assertEquals(0,user.get("roles").size());write("POST","/api/v1/users/"+id+"/enable",admin,Map.of("expectedLockVersion","4"),400);
        write("PUT","/api/v1/users/"+id+"/roles",admin,Map.of("roles",List.of("VIEWER"),"expectedLockVersion","4"),200);user=write("POST","/api/v1/users/"+id+"/enable",admin,Map.of("expectedLockVersion","5"),200);assertEquals("6",user.get("lockVersion").asText());
        JsonNode stale=write("PATCH","/api/v1/users/"+id,admin,Map.of("displayName","Stale edit","expectedLockVersion","0"),409);assertEquals("LOCK_VERSION_CONFLICT",stale.get("code").asText());assertEquals("6",stale.get("currentLockVersion").asText());
        write("PATCH","/api/v1/users/"+id,admin,Map.of("passwordHash","forbidden","expectedLockVersion","6"),400);write("POST","/api/v1/users",admin,Map.of("username",name,"email","another@example.invalid","displayName","duplicate","initialPassword",PASSWORD,"roles",List.of("VIEWER")),409);
        write("POST","/api/v1/users",admin,Map.of("username","boundary_"+UUID.randomUUID(),"email","boundary@example.invalid","displayName","boundary","initialPassword","A".repeat(73),"roles",List.of("VIEWER")),400);assertEquals(before+1,count("User"));
    }
    @Test void draftPatchMetadataTagNormalizationAndAndFilteredNumericPages()throws Exception {
        Created engineer=newUser("REQUIREMENT_ENGINEER"),assignee=newUser("VIEWER");MockHttpSession session=login(engineer.username(),PASSWORD),admin=adminSession();String marker="query_"+UUID.randomUUID();long versions=count("RequirementVersion");
        write("POST","/api/v1/requirements",admin,draft(marker),403);JsonNode req=write("POST","/api/v1/requirements",session,draft(marker),201);String id=req.get("requirementId").asText(),key=req.get("requirementKey").asText();assertEquals("DRAFT",req.get("status").asText());assertTrue(req.get("source").isNull());assertTrue(req.get("currentVersionId").isNull());assertEquals(Set.of("userId","displayName","accountStatus"),fieldNames(req.get("creator")));assertTrue(key.length()<=32);
        req=write("PATCH","/api/v1/requirements/"+id+"/content",session,Map.of("source","draft source","expectedLockVersion","0"),200);assertEquals("draft body",req.get("description").asText());
        Map<String,Object> clear=new HashMap<>();clear.put("source",null);clear.put("expectedLockVersion","1");req=write("PATCH","/api/v1/requirements/"+id+"/content",session,clear,200);assertTrue(req.get("source").isNull());assertEquals(key,req.get("requirementKey").asText());
        Map<String,Object> invalid=new HashMap<>();invalid.put("title",null);invalid.put("expectedLockVersion","2");write("PATCH","/api/v1/requirements/"+id+"/content",session,invalid,400);write("PATCH","/api/v1/requirements/"+id+"/content",session,Map.of("creatorId","1","expectedLockVersion","2"),400);write("PATCH","/api/v1/requirements/"+id+"/content",session,Map.of("title","stale","expectedLockVersion","0"),409);
        String tagName="tag_"+UUID.randomUUID();JsonNode tag=write("POST","/api/v1/tags",session,Map.of("name","  "+tagName+"  ","description","initial"),201);String tagId=tag.get("tagId").asText();assertEquals(tagName,tag.get("name").asText());write("POST","/api/v1/tags",session,Map.of("name",tagName),409);
        Map<String,Object> clearTag=new HashMap<>();clearTag.put("description",null);assertTrue(write("PATCH","/api/v1/tags/"+tagId,session,clearTag,200).get("description").isNull());write("PATCH","/api/v1/tags/"+tagId,session,Map.of("name",tagName,"lockVersion","0"),400);
        req=write("PATCH","/api/v1/requirements/"+id+"/metadata",session,Map.of("assigneeId",Long.toString(assignee.user().userId()),"tagIds",List.of(tagId),"expectedLockVersion","2"),200);assertEquals("3",req.get("lockVersion").asText());assertEquals(Long.toString(assignee.user().userId()),req.get("assignee").get("userId").asText());assertEquals(1,req.get("tags").size());assertTrue(req.get("currentVersionId").isNull());
        JsonNode page=getJson("/api/v1/requirements?keyword="+marker+"&status=DRAFT&kind=FUNCTIONAL&level=USER&priority=HIGH&tag="+tagId,session,200);assertTrue(page.get("totalElements").isIntegralNumber());assertEquals(1,page.get("items").size());assertEquals(0,getJson("/api/v1/requirements?keyword="+marker+"&priority=LOW&tag="+tagId,session,200).get("items").size());getJson("/api/v1/requirements?status=UNDEFINED",session,400);getJson("/api/v1/requirements?size=101",session,400);getJson("/api/v1/tags?page=-1",session,400);
        write("POST","/api/v1/users/"+assignee.user().userId()+"/disable",admin,Map.of("expectedLockVersion","0"),200);assertEquals("INVALID_INPUT",write("PATCH","/api/v1/requirements/"+id+"/metadata",session,Map.of("assigneeId",Long.toString(assignee.user().userId()),"expectedLockVersion","3"),400).get("code").asText());
        Map<String,Object> clearMetadata=new HashMap<>();clearMetadata.put("assigneeId",null);clearMetadata.put("tagIds",List.of());clearMetadata.put("expectedLockVersion","3");req=write("PATCH","/api/v1/requirements/"+id+"/metadata",session,clearMetadata,200);assertTrue(req.get("assigneeId").isNull());assertTrue(req.get("assignee").isNull());assertEquals(0,req.get("tags").size());assertEquals(versions,count("RequirementVersion"));assertTrue(getJson("/api/v1/tags?name="+tagName,session,200).get("totalElements").isIntegralNumber());
    }
    @Test void commentsRespectRoleAuthorLogicalDeletionAndPreserveRequirementRevision()throws Exception {
        Created engineer=newUser("REQUIREMENT_ENGINEER"),member=newUser("PROJECT_MEMBER"),viewer=newUser("VIEWER"),reviewer=newUser("REVIEWER");MockHttpSession eng=login(engineer.username(),PASSWORD),mem=login(member.username(),PASSWORD),view=login(viewer.username(),PASSWORD),rev=login(reviewer.username(),PASSWORD),admin=adminSession();JsonNode req=write("POST","/api/v1/requirements",eng,draft("comment_"+UUID.randomUUID()),201);String reqId=req.get("requirementId").asText();long versions=count("RequirementVersion");
        write("POST","/api/v1/requirements/"+reqId+"/comments",view,Map.of("content","denied viewer"),403);write("POST","/api/v1/requirements/"+reqId+"/comments",admin,Map.of("content","denied admin only"),403);write("POST","/api/v1/requirements/"+reqId+"/comments",rev,Map.of("content","reviewer comment"),201);write("POST","/api/v1/requirements/"+reqId+"/comments",eng,Map.of("content","engineer comment"),201);
        String content="member retained body";JsonNode comment=write("POST","/api/v1/requirements/"+reqId+"/comments",mem,Map.of("content",content),201);String id=comment.get("commentId").asText();write("DELETE","/api/v1/comments/"+id,eng,null,403);write("DELETE","/api/v1/comments/"+id,mem,null,204);write("DELETE","/api/v1/comments/"+id,mem,null,409);
        JsonNode page=getJson("/api/v1/requirements/"+reqId+"/comments",view,200);assertTrue(page.get("totalElements").isIntegralNumber());JsonNode deleted=null;for(JsonNode row:page.get("items"))if(row.get("commentId").asText().equals(id))deleted=row;assertNotNull(deleted);assertEquals(1,deleted.get("isDeleted").asInt());assertTrue(deleted.get("content").isNull());assertEquals(content,em.createNativeQuery("SELECT content FROM `Comment` WHERE commentId=:id").setParameter("id",Long.parseLong(id)).getSingleResult());assertEquals("0",getJson("/api/v1/requirements/"+reqId,view,200).get("lockVersion").asText());assertEquals(versions,count("RequirementVersion"));
    }
    @Test void existingSessionsObserveRoleRevocationDisableAndLegitimateSelfDisable()throws Exception {
        Created engineer=newUser("REQUIREMENT_ENGINEER"),selfAdmin=newUser("ADMIN");MockHttpSession session=login(engineer.username(),PASSWORD),admin=adminSession();write("POST","/api/v1/requirements",session,draft("before revoke "+UUID.randomUUID()),201);
        write("PUT","/api/v1/users/"+engineer.user().userId()+"/roles",admin,Map.of("roles",List.of("VIEWER"),"expectedLockVersion","0"),200);write("POST","/api/v1/requirements",session,draft("after revoke"),403);assertEquals("VIEWER",getJson("/api/v1/auth/session",session,200).get("roles").get(0).asText());getJson("/api/v1/users",session,403);
        write("POST","/api/v1/users/"+engineer.user().userId()+"/disable",admin,Map.of("expectedLockVersion","1"),200);assertEquals("ACCOUNT_DISABLED",getJson("/api/v1/auth/session",session,403).get("code").asText());assertTrue(session.isInvalid());
        MockHttpSession self=login(selfAdmin.username(),PASSWORD);assertEquals("DISABLED",write("POST","/api/v1/users/"+selfAdmin.user().userId()+"/disable",self,Map.of("expectedLockVersion","0"),200).get("accountStatus").asText());assertEquals(1,((Number)em.createNativeQuery("SELECT COUNT(*) FROM `AuditEvent` WHERE actorId=:id AND action='USER_DISABLE' AND outcome='SUCCESS'").setParameter("id",selfAdmin.user().userId()).getSingleResult()).intValue());
    }
    @Test void businessAndSuccessAuditRollbackTogetherAndConstraintFailureLeavesNoPartialUser() {
        Created engineer=newUser("REQUIREMENT_ENGINEER");act(engineer.user().userId());Actor actor=access.requireEnabledActor(engineer.user().userId());long before=count("Requirement"),audits=count("AuditEvent");assertThrows(IllegalStateException.class,()->new TransactionTemplate(manager).executeWithoutResult(status->{transactions.create(actor,"rollback synthetic","body","USER","FUNCTIONAL","HIGH",null,null,null);throw new IllegalStateException("WAVE1_DEVELOPER_ROLLBACK_PROBE");}));assertEquals(before,count("Requirement"));assertEquals(audits,count("AuditEvent"));
        act(adminId());long users=count("User"),links=count("UserRole");assertThrows(org.springframework.dao.DataIntegrityViolationException.class,()->administration.create(engineer.username(),"duplicate_"+UUID.randomUUID()+"@example.invalid","duplicate",PASSWORD,List.of("VIEWER")));assertEquals(users,count("User"));assertEquals(links,count("UserRole"));assertEquals(audits+1,count("AuditEvent"));
    }
    @Test void simultaneousStaleDraftWritersProduceOneSuccessOneConflictWithoutRetry()throws Exception {
        Created engineer=newUser("REQUIREMENT_ENGINEER");act(engineer.user().userId());String id=Long.toString(requirements.create("race synthetic","body","USER","FUNCTIONAL","HIGH",null,null,null).requirement().requirementId());var barrier=new CyclicBarrier(2);
        try(var pool=Executors.newFixedThreadPool(2)) {
            List<Future<String>> futures=new ArrayList<>();for(String title:List.of("writer A","writer B"))futures.add(pool.submit(()->{act(engineer.user().userId());try{barrier.await(10,TimeUnit.SECONDS);requirements.content(id,Map.of("title",title,"expectedLockVersion","0"));return "SUCCESS";}catch(RmsException failure){return failure.code().name();}finally{SecurityContextHolder.clearContext();}}));
            List<String> outcomes=new ArrayList<>();for(var future:futures)outcomes.add(future.get(20,TimeUnit.SECONDS));Collections.sort(outcomes);assertEquals(List.of("LOCK_VERSION_CONFLICT","SUCCESS"),outcomes);
        }
        act(engineer.user().userId());assertEquals(1,requirements.read(id).requirement().lockVersion());assertEquals(1,((Number)em.createNativeQuery("SELECT COUNT(*) FROM `AuditEvent` WHERE targetType='REQUIREMENT' AND targetId=:id AND action='REQUIREMENT_CONTENT_EDIT' AND outcome='SUCCESS'").setParameter("id",id).getSingleResult()).intValue());assertEquals(1,((Number)em.createNativeQuery("SELECT COUNT(*) FROM `AuditEvent` WHERE targetType='REQUIREMENT' AND targetId=:id AND action='REQUIREMENT_CONTENT_EDIT' AND outcome='FAILED'").setParameter("id",id).getSingleResult()).intValue());
    }
    @Test void scalarTypeAndUnknownFieldAttacksAreRejectedAndDirectoryRemainsAdminOnly()throws Exception {
        Created engineer=newUser("REQUIREMENT_ENGINEER");MockHttpSession session=login(engineer.username(),PASSWORD),admin=adminSession();getJson("/api/v1/users",session,403);write("POST","/api/v1/requirements",session,Map.of("title",12,"description","body","level","USER","kind","FUNCTIONAL","priority","HIGH"),400);write("POST","/api/v1/requirements",session,Map.of("title","injected","description","body","level","USER","kind","FUNCTIONAL","priority","HIGH","creatorId","1"),400);write("POST","/api/v1/tags",session,Map.of("name","   "),400);write("PUT","/api/v1/users/"+engineer.user().userId()+"/roles",admin,Map.of("roles",List.of("UNKNOWN"),"expectedLockVersion","0"),400);getJson("/api/v1/requirements/9223372036854775808",session,400);getJson("/api/v1/requirements/01",session,400);getJson("/api/v1/requirements/9223372036854775807",session,404);getJson("/api/v1/requirements?size=0",session,400);
    }
    @Test void nonDraftAndWithdrawnOwnerGuardsHoldWithRollbackOnlyDeveloperFixtures() {
        Created engineer=newUser("REQUIREMENT_ENGINEER");act(engineer.user().userId());Actor actor=access.requireEnabledActor(engineer.user().userId());String marker="owner_guard_"+UUID.randomUUID();var req=requirements.create(marker,"body","USER","FUNCTIONAL","HIGH",null,null,null);long id=req.requirement().requirementId();
        for(String state:List.of("UNDER_REVIEW","REJECTED"))new TransactionTemplate(manager).executeWithoutResult(status->{em.createNativeQuery("UPDATE `Requirement` SET status=:state,firstSubmittedAt=UTC_TIMESTAMP(6) WHERE requirementId=:id").setParameter("state",state).setParameter("id",id).executeUpdate();em.clear();assertEquals(ErrorCode.STATE_CONFLICT,assertThrows(RmsException.class,()->transactions.content(actor,id,Map.of("title","forbidden state edit","expectedLockVersion","0"))).code());status.setRollbackOnly();});
        new TransactionTemplate(manager).executeWithoutResult(status->{em.createNativeQuery("UPDATE `Requirement` SET isWithdrawn=1,withdrawnBy=:actor,withdrawnAt=UTC_TIMESTAMP(6) WHERE requirementId=:id").setParameter("actor",actor.userId()).setParameter("id",id).executeUpdate();em.clear();assertEquals(ErrorCode.STATE_CONFLICT,assertThrows(RmsException.class,()->transactions.content(actor,id,Map.of("title","forbidden withdrawn edit","expectedLockVersion","0"))).code());assertEquals(ErrorCode.STATE_CONFLICT,assertThrows(RmsException.class,()->transactions.metadata(actor,id,Map.of("tagIds",List.of(),"expectedLockVersion","0"))).code());assertEquals(ErrorCode.STATE_CONFLICT,assertThrows(RmsException.class,()->commentTransactions.create(actor,id,"forbidden withdrawn comment")).code());assertEquals(0,requirements.list(0,20,marker,null,null,null,null,null).items().size());assertEquals(1,requirements.read(Long.toString(id)).requirement().isWithdrawn());status.setRollbackOnly();});
        em.clear();assertEquals("DRAFT",requirements.read(Long.toString(id)).requirement().status());assertEquals(0,requirements.read(Long.toString(id)).requirement().isWithdrawn());
    }
    @Test void simultaneousOwnCommentDeletionAppendsOneSuccessAndOneStateConflict()throws Exception {
        Created engineer=newUser("REQUIREMENT_ENGINEER");act(engineer.user().userId());String requirementId=Long.toString(requirements.create("delete race","body","USER","FUNCTIONAL","HIGH",null,null,null).requirement().requirementId());String id=Long.toString(comments.create(requirementId,"retained concurrent body").commentId());var barrier=new CyclicBarrier(2);
        try(var pool=Executors.newFixedThreadPool(2)) { List<Future<String>> futures=new ArrayList<>();for(int i=0;i<2;i++)futures.add(pool.submit(()->{act(engineer.user().userId());try{barrier.await(10,TimeUnit.SECONDS);comments.delete(id);return "SUCCESS";}catch(RmsException failure){return failure.code().name();}finally{SecurityContextHolder.clearContext();}}));List<String> outcomes=new ArrayList<>();for(var future:futures)outcomes.add(future.get(20,TimeUnit.SECONDS));Collections.sort(outcomes);assertEquals(List.of("STATE_CONFLICT","SUCCESS"),outcomes); }
        assertEquals(1,((Number)em.createNativeQuery("SELECT COUNT(*) FROM `AuditEvent` WHERE targetType='COMMENT' AND targetId=:id AND action='COMMENT_DELETE' AND outcome='SUCCESS'").setParameter("id",id).getSingleResult()).intValue());assertEquals("retained concurrent body",em.createNativeQuery("SELECT content FROM `Comment` WHERE commentId=:id").setParameter("id",Long.parseLong(id)).getSingleResult());
    }
    private static Set<String> fieldNames(JsonNode node) { Set<String> names=new HashSet<>();node.fieldNames().forEachRemaining(names::add);return names; }
}
