package com.example.rms;
import com.example.rms.user.application.*;
import com.example.rms.user.application.contract.UserAccessService;
import com.example.rms.requirement.application.*;
import com.example.rms.requirement.application.contract.RequirementMutationService;
import com.example.rms.review.application.*;
import com.example.rms.version.application.contract.VersionAppendService;
import com.example.rms.shared.application.Actor;
import com.example.rms.shared.domain.*;
import com.fasterxml.jackson.databind.*;
import jakarta.persistence.EntityManager;
import java.util.*;
import java.util.concurrent.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.autoconfigure.web.servlet.*;
import org.springframework.mock.web.MockHttpSession;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.test.web.servlet.*;
import org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
import static org.junit.jupiter.api.Assertions.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
/** Developer-owned synthetic probes; retained real MySQL, no acceptance/oracle inputs. */
@SpringBootTest @AutoConfigureMockMvc(print=MockMvcPrint.NONE)
class Wave2DeveloperIntegrationTest {
    @Autowired MockMvc mvc;@Autowired ObjectMapper json;@Autowired EntityManager em;@Autowired UserAdministrationService administration;@Autowired UserAccessService access;@Autowired RequirementService requirements;@Autowired ReviewService reviews;@Autowired ReviewTransactions writes;@Autowired PlatformTransactionManager manager;@Autowired VersionAppendService versions;@Autowired RequirementMutationService mutations;
    private static final String PASSWORD="Wave two developer é";
    private record Created(String username,UserData user) {}
    @AfterEach void cleanupContext() { org.springframework.security.test.context.TestSecurityContextHolder.clearContext(); }
    private long adminId() { return ((Number)em.createNativeQuery("SELECT MIN(u.userId) FROM `User` u JOIN `UserRole` ur ON ur.userId=u.userId JOIN `Role` r ON r.roleId=ur.roleId WHERE u.accountStatus='ENABLED' AND r.roleCode='ADMIN'").getSingleResult()).longValue(); }
    private void act(long id) { Actor actor=access.requireEnabledActor(id);SecurityContextHolder.getContext().setAuthentication(UsernamePasswordAuthenticationToken.authenticated(actor,null,List.of())); }
    private Created user(String... roles) { act(adminId());String name="w2_"+UUID.randomUUID().toString().replace("-","");var result=new Created(name,administration.create(name,name+"@example.invalid","Wave two synthetic",PASSWORD,List.of(roles)));org.springframework.security.test.context.TestSecurityContextHolder.clearContext();return result; }
    private MockHttpSession login(Created u)throws Exception { org.springframework.security.test.context.TestSecurityContextHolder.clearContext();var csrf=mvc.perform(get("/api/v1/auth/csrf")).andExpect(status().isOk()).andReturn();var session=(MockHttpSession)csrf.getRequest().getSession(false);mvc.perform(post("/api/v1/auth/login").session(session).header("X-CSRF-TOKEN",read(csrf).get("token").asText()).contentType("application/json").content(json.writeValueAsString(Map.of("login",u.username(),"password",PASSWORD)))).andExpect(status().isOk());return session; }
    private JsonNode read(MvcResult r)throws Exception { return json.readTree(r.getResponse().getContentAsString()); }
    private JsonNode postJson(String path,MockHttpSession s,Object body,int expected)throws Exception { org.springframework.security.test.context.TestSecurityContextHolder.clearContext();String csrf=read(mvc.perform(get("/api/v1/auth/csrf").session(s)).andExpect(status().isOk()).andReturn()).get("token").asText();return read(mvc.perform(post(path).session(s).header("X-CSRF-TOKEN",csrf).contentType("application/json").content(json.writeValueAsString(body))).andExpect(status().is(expected)).andReturn()); }
    private JsonNode patch(String path,MockHttpSession s,Object body,int expected)throws Exception { org.springframework.security.test.context.TestSecurityContextHolder.clearContext();String csrf=read(mvc.perform(get("/api/v1/auth/csrf").session(s)).andExpect(status().isOk()).andReturn()).get("token").asText();return read(mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.patch(path).session(s).header("X-CSRF-TOKEN",csrf).contentType("application/json").content(json.writeValueAsString(body))).andExpect(status().is(expected)).andReturn()); }
    private JsonNode getJson(String path,MockHttpSession s,int expected)throws Exception { org.springframework.security.test.context.TestSecurityContextHolder.clearContext();return read(mvc.perform(get(path).session(s)).andExpect(status().is(expected)).andReturn()); }
    private Map<String,Object> content(String title) { return Map.of("title",title,"description","Explicit observable behavior","level","USER","kind","FUNCTIONAL","priority","HIGH","source","Synthetic stakeholder interview","rationale","Prevent data loss","acceptanceCriteria","Given a valid form, saving returns its saved record with unchanged values."); }
    private JsonNode create(MockHttpSession s)throws Exception { return postJson("/api/v1/requirements",s,content("w2_"+UUID.randomUUID()),201); }
    private String path(JsonNode r) { return "/api/v1/requirements/"+r.get("requirementId").asText(); }
    private JsonNode submit(JsonNode r,MockHttpSession s)throws Exception { return postJson(path(r)+"/submit",s,Map.of("expectedLockVersion",r.get("lockVersion").asText()),201); }
    private JsonNode decision(JsonNode review,MockHttpSession s,String value,String revision,String comment,int expected)throws Exception { Map<String,Object> body=new HashMap<>();body.put("decision",value);body.put("expectedRequirementLockVersion",revision);body.put("comment",comment);return postJson("/api/v1/requirement-reviews/"+review.get("reviewId").asText()+"/decision",s,body,expected); }
    private long count(String table,String where,long id) { return ((Number)em.createNativeQuery("SELECT COUNT(*) FROM `"+table+"` WHERE "+where+"=:id").setParameter("id",id).getSingleResult()).longValue(); }
    private long auditCount(String target,String action,String outcome) { return ((Number)em.createNativeQuery("SELECT COUNT(*) FROM `AuditEvent` WHERE targetId=:id AND action=:action AND outcome=:outcome").setParameter("id",target).setParameter("action",action).setParameter("outcome",outcome).getSingleResult()).longValue(); }
    @Test void completeRoundSnapshotsResubmissionAndAtomicInitialApproval()throws Exception {
        var engineer=user("REQUIREMENT_ENGINEER");var reviewer=user("REVIEWER");MockHttpSession eng=login(engineer),rev=login(reviewer);var r=create(eng);String p=path(r);
        var empty=getJson(p+"/versions",eng,200);assertTrue(empty.get("totalElements").isIntegralNumber());assertEquals(0,empty.get("items").size());var first=submit(r,eng);assertEquals(1,first.get("roundNo").asInt());assertEquals("PENDING",first.get("reviewStatus").asText());assertTrue(first.get("reviewId").isTextual());assertTrue(first.get("reviewerId").isNull());assertFalse(first.has("activeRequirementId"));String submitted=getJson(p,eng,200).get("firstSubmittedAt").asText();
        assertEquals("STATE_CONFLICT",patch(p+"/content",eng,Map.of("title","blocked","expectedLockVersion","1"),409).get("code").asText());assertEquals(0,getJson(p+"/versions",eng,200).get("items").size());
        postJson(p+"/submit",eng,Map.of("expectedLockVersion","1"),409);decision(first,rev,"REQUEST_CHANGES","1"," ",400);var returned=decision(first,rev,"REQUEST_CHANGES","1","Specify failure recovery",200);assertTrue(returned.get("version").isNull());assertEquals("DRAFT",returned.get("requirement").get("status").asText());assertEquals("2",returned.get("requirement").get("lockVersion").asText());decision(first,rev,"REJECT","2","Cannot overwrite",409);
        var edited=patch(p+"/content",eng,Map.of("title","Revised snapshot title","source","Updated source","expectedLockVersion","2"),200);var second=submit(edited,eng);assertEquals(2,second.get("roundNo").asInt());assertNotEquals(first.get("reviewId"),second.get("reviewId"));assertEquals(submitted,getJson(p,eng,200).get("firstSubmittedAt").asText());
        patch(p+"/metadata",eng,Map.of("tagIds",List.of(),"expectedLockVersion","4"),200);var approved=decision(second,rev,"APPROVE","5",null,200);JsonNode v=approved.get("version"),parent=approved.get("requirement");assertEquals(1,v.get("versionNo").asInt());assertTrue(v.get("versionId").isTextual());assertEquals(second.get("reviewId"),v.get("initialReviewId"));assertTrue(v.get("appliedChangeRequestId").isNull());assertEquals(Long.toString(reviewer.user().userId()),v.get("createdBy").asText());assertEquals("APPROVED",parent.get("status").asText());assertEquals(v.get("versionId"),parent.get("currentVersionId"));assertEquals("6",parent.get("lockVersion").asText());
        for(String field:List.of("title","description","level","kind","priority","source","rationale","acceptanceCriteria")){assertEquals(second.get("snapshot"+Character.toUpperCase(field.charAt(0))+field.substring(1)),v.get(field));assertEquals(v.get(field),parent.get(field));}
        Object[] audit=(Object[])em.createNativeQuery("SELECT CAST(beforeData AS CHAR),CAST(afterData AS CHAR) FROM `AuditEvent` WHERE targetType='REVIEW' AND targetId=:id AND action='REQUIREMENT_REVIEW_DECISION' AND outcome='SUCCESS'").setParameter("id",second.get("reviewId").asText()).getSingleResult();var beforeAudit=json.readTree((String)audit[0]);var afterAudit=json.readTree((String)audit[1]);assertTrue(beforeAudit.has("currentVersionId"));assertTrue(beforeAudit.get("currentVersionId").isNull());assertEquals(v.get("versionId"),afterAudit.get("currentVersionId"));assertEquals(v.get("initialReviewId"),afterAudit.get("reviewId"));assertEquals("UNDER_REVIEW",beforeAudit.get("status").asText());assertEquals("APPROVED",afterAudit.get("status").asText());
        var history=getJson(p+"/reviews",eng,200);assertTrue(history.get("totalElements").isIntegralNumber());assertEquals(2,history.get("items").size());assertEquals(first.get("snapshotTitle"),history.get("items").get(0).get("snapshotTitle"));assertEquals("REQUEST_CHANGES",history.get("items").get(0).get("decision").asText());assertEquals("Specify failure recovery",history.get("items").get(0).get("comment").asText());assertEquals(1,getJson(p+"/versions",eng,200).get("items").size());assertEquals(v,getJson(p+"/versions/"+v.get("versionId").asText(),eng,200));decision(second,rev,"APPROVE","6",null,409);assertEquals(1,count("RequirementVersion","requirementId",r.get("requirementId").asLong()));
    }
    @Test void rejectionReopensOnlyRejectedAndPreservesCompletedHistory()throws Exception {
        MockHttpSession eng=login(user("REQUIREMENT_ENGINEER")),rev=login(user("REVIEWER"));var r=create(eng);String p=path(r);postJson(p+"/reopen",eng,Map.of("expectedLockVersion","0"),409);var round=submit(r,eng);decision(round,rev,"REJECT","1",null,400);var result=decision(round,rev,"REJECT","1","Rejected on review",200);assertEquals("REJECTED",result.get("requirement").get("status").asText());assertTrue(result.get("version").isNull());String submitted=result.get("requirement").get("firstSubmittedAt").asText();
        var reopened=postJson(p+"/reopen",eng,Map.of("expectedLockVersion","2"),200);assertEquals("DRAFT",reopened.get("status").asText());assertEquals(submitted,reopened.get("firstSubmittedAt").asText());var again=submit(reopened,eng);assertEquals(2,again.get("roundNo").asInt());assertEquals("Rejected on review",getJson(p+"/reviews",eng,200).get("items").get(0).get("comment").asText());assertEquals(0,getJson(p+"/versions",eng,200).get("items").size());
    }
    @Test void completenessStrictInputsAndAllRoleSelfReviewExclusion()throws Exception {
        Created creator=user("ADMIN","REQUIREMENT_ENGINEER","REVIEWER","PROJECT_MEMBER","VIEWER"),other=user("REVIEWER"),viewer=user("VIEWER");MockHttpSession own=login(creator),rev=login(other),view=login(viewer);var fields=new HashMap<>(content("Incomplete synthetic"));fields.remove("source");var r=postJson("/api/v1/requirements",own,fields,201);String p=path(r);assertEquals("INCOMPLETE_CONTENT",postJson(p+"/submit",own,Map.of("expectedLockVersion","0"),400).get("code").asText());assertEquals(0,count("RequirementReview","requirementId",r.get("requirementId").asLong()));assertTrue(getJson(p,own,200).get("firstSubmittedAt").isNull());
        r=patch(p+"/content",own,Map.of("source","Known source","expectedLockVersion","0"),200);postJson(p+"/submit",own,Map.of("expectedLockVersion",1),400);postJson(p+"/submit",own,Map.of("expectedLockVersion","1","submittedBy","1"),400);var round=submit(r,own);assertEquals("SELF_REVIEW",decision(round,own,"APPROVE","2",null,403).get("code").asText());assertEquals("PENDING",getJson(p+"/reviews",own,200).get("items").get(0).get("reviewStatus").asText());assertEquals("FORBIDDEN",decision(round,view,"APPROVE","2",null,403).get("code").asText());getJson("/api/v1/reviews/pending",view,403);var pending=getJson("/api/v1/reviews/pending?size=100",rev,200);assertTrue(pending.get("totalElements").isIntegralNumber());
        postJson("/api/v1/requirement-reviews/"+round.get("reviewId").asText()+"/decision",rev,Map.of("decision","APPROVE","expectedRequirementLockVersion","2","reviewerId","1"),400);decision(round,rev,"UNKNOWN","2",null,400);decision(round,rev,"APPROVE","0",null,409);
        act(adminId());administration.roles(Long.toString(other.user().userId()),Map.of("roles",List.of("VIEWER"),"expectedLockVersion","0"));org.springframework.security.test.context.TestSecurityContextHolder.clearContext();decision(round,rev,"APPROVE","2",null,403);assertEquals(0,count("RequirementVersion","requirementId",r.get("requirementId").asLong()));
    }
    @Test void versionBoundImplementVerifyDescriptionsAndRoleStateGuards()throws Exception {
        MockHttpSession eng=login(user("REQUIREMENT_ENGINEER")),rev=login(user("REVIEWER")),member=login(user("PROJECT_MEMBER")),view=login(user("VIEWER"));var r=create(eng);String p=path(r);postJson(p+"/implement",member,Map.of("expectedVersionId","1","expectedLockVersion","0","description"," premature"),409);var round=submit(r,eng);var result=decision(round,rev,"APPROVE","1","Approved",200);String version=result.get("version").get("versionId").asText();
        postJson(p+"/verify",member,Map.of("expectedVersionId",version,"expectedLockVersion","2","description","Skip rejected"),409);postJson(p+"/implement",eng,Map.of("expectedVersionId",version,"expectedLockVersion","2","description","Wrong role"),403);assertEquals("BASE_VERSION_STALE",postJson(p+"/implement",member,Map.of("expectedVersionId","9223372036854775807","expectedLockVersion","2","description","Wrong baseline"),409).get("code").asText());postJson(p+"/implement",member,Map.of("expectedVersionId",version,"expectedLockVersion","2","description"," "),400);
        var implemented=postJson(p+"/implement",member,Map.of("expectedVersionId",version,"expectedLockVersion","2","description","Implemented version on synthetic branch"),200);assertEquals("IMPLEMENTED",implemented.get("status").asText());assertEquals("3",implemented.get("lockVersion").asText());postJson(p+"/verify",member,Map.of("expectedVersionId",version,"expectedLockVersion","2","description","Stale revision"),409);var verified=postJson(p+"/verify",member,Map.of("expectedVersionId",version,"expectedLockVersion","3","description","Validated observable acceptance behavior"),200);assertEquals("VERIFIED",verified.get("status").asText());assertEquals("4",verified.get("lockVersion").asText());assertEquals(version,verified.get("currentVersionId").asText());assertEquals(1,getJson(p+"/versions",view,200).get("items").size());
        JsonNode audit=json.readTree((String)em.createNativeQuery("SELECT CAST(afterData AS CHAR) FROM `AuditEvent` WHERE targetId=:id AND action='REQUIREMENT_VERIFY' AND outcome='SUCCESS'").setParameter("id",r.get("requirementId").asText()).getSingleResult());assertEquals(version,audit.get("currentVersionId").asText());assertEquals("Validated observable acceptance behavior",audit.get("explanation").asText());
        var other=create(eng);getJson(path(other)+"/versions/"+version,view,404);getJson("/api/v1/requirements/9223372036854775807/versions",view,404);getJson(p+"/versions?page=-1",view,400);getJson(p+"/reviews?size=101",view,400);postJson(p+"/reopen",eng,Map.of("expectedLockVersion","4"),409);
    }
    @Test void initialApprovalEntirePhysicalTransactionAndSuccessAuditRollBack() {
        Created engineer=user("REQUIREMENT_ENGINEER"),reviewer=user("REVIEWER");act(engineer.user().userId());var r=requirements.create("Atomic rollback synthetic","observable body","USER","FUNCTIONAL","HIGH","source","rationale","Saving shows unchanged values").requirement();String id=Long.toString(r.requirementId());var round=reviews.submit(id,"0");act(reviewer.user().userId());Actor actor=access.requireEnabledActor(reviewer.user().userId());String target=Long.toString(round.reviewId());long audits=auditCount(target,"REQUIREMENT_REVIEW_DECISION","SUCCESS");
        assertThrows(IllegalStateException.class,()->new TransactionTemplate(manager).executeWithoutResult(status->{var result=writes.decide(actor,round.reviewId(),"APPROVE",null,"1");assertNotNull(result.version());assertEquals("APPROVED",result.requirement().status());throw new IllegalStateException("WAVE2_DEVELOPER_AFTER_ALL_WRITES_ROLLBACK");}));
        assertEquals(0,count("RequirementVersion","requirementId",r.requirementId()));act(engineer.user().userId());var parent=requirements.read(id).requirement();assertEquals("UNDER_REVIEW",parent.status());assertEquals(1,parent.lockVersion());assertNull(parent.currentVersionId());assertEquals("PENDING",reviews.history(id,0,20).items().getFirst().reviewStatus());assertEquals(audits,auditCount(target,"REQUIREMENT_REVIEW_DECISION","SUCCESS"));assertThrows(org.springframework.transaction.IllegalTransactionStateException.class,()->versions.appendInitial(r.requirementId(),round.reviewId(),round.content(),reviewer.user().userId(),java.time.Instant.now()));assertThrows(org.springframework.transaction.IllegalTransactionStateException.class,()->mutations.installInitialVersion(r.requirementId(),1,round.content(),java.time.Instant.now()));
        act(reviewer.user().userId());assertEquals("APPROVED",reviews.decide(target,"APPROVE",null,"1").requirement().status());
    }
    @Test void concurrentSubmissionsAndDecisionsHaveExactlyOneSuccessWithoutReplay()throws Exception {
        Created engineer=user("REQUIREMENT_ENGINEER"),reviewer=user("REVIEWER");act(engineer.user().userId());var r=requirements.create("Concurrent review synthetic","body","USER","FUNCTIONAL","HIGH","source","rationale","Saving returns a saved record").requirement();String id=Long.toString(r.requirementId());assertEquals(List.of("LOCK_VERSION_CONFLICT","SUCCESS"),race(engineer.user().userId(),()->reviews.submit(id,"0")));assertEquals(1,count("RequirementReview","requirementId",r.requirementId()));act(engineer.user().userId());var round=reviews.history(id,0,20).items().getFirst();String target=Long.toString(round.reviewId());assertEquals(List.of("LOCK_VERSION_CONFLICT","SUCCESS"),race(reviewer.user().userId(),()->reviews.decide(target,"APPROVE",null,"1")));assertEquals(1,count("RequirementVersion","requirementId",r.requirementId()));assertEquals(1,auditCount(target,"REQUIREMENT_REVIEW_DECISION","SUCCESS"));assertEquals(1,auditCount(target,"REQUIREMENT_REVIEW_DECISION","FAILED"));act(engineer.user().userId());assertEquals(2,requirements.read(id).requirement().lockVersion());
    }
    private List<String> race(long actor,Callable<?> command)throws Exception { var barrier=new CyclicBarrier(2);try(var pool=Executors.newFixedThreadPool(2)){List<Future<String>> futures=new ArrayList<>();for(int i=0;i<2;i++)futures.add(pool.submit(()->{act(actor);try{barrier.await(10,TimeUnit.SECONDS);command.call();return "SUCCESS";}catch(RmsException e){return e.code().name();}finally{SecurityContextHolder.clearContext();}}));List<String> result=new ArrayList<>();for(var f:futures)result.add(f.get(20,TimeUnit.SECONDS));Collections.sort(result);return result;} }
}
