package com.example.rms;
import com.example.rms.user.application.*;
import com.example.rms.user.application.contract.UserAccessService;
import com.example.rms.requirement.application.*;
import com.example.rms.requirement.application.contract.RequirementMutationService;
import com.example.rms.review.application.*;
import com.example.rms.change.application.*;
import com.example.rms.version.application.contract.VersionAppendService;
import com.example.rms.shared.application.Actor;
import com.example.rms.shared.domain.*;
import com.fasterxml.jackson.databind.*;
import jakarta.persistence.EntityManager;
import java.util.*;
import java.util.concurrent.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.autoconfigure.web.servlet.*;
import org.springframework.mock.web.MockHttpSession;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.test.web.servlet.*;
import org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
import static org.junit.jupiter.api.Assertions.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
/** Developer-owned synthetic probes; retained real MySQL, no acceptance/oracle inputs. */
@SpringBootTest @AutoConfigureMockMvc(print=MockMvcPrint.NONE)
class Wave3DeveloperIntegrationTest {
    @Autowired MockMvc mvc;@Autowired ObjectMapper json;@Autowired EntityManager em;@Autowired UserAdministrationService administration;@Autowired UserAccessService access;@Autowired RequirementService requirements;@Autowired ReviewService reviews;@Autowired ChangeTransactions writes;@Autowired ChangeService changes;@Autowired PlatformTransactionManager manager;@Autowired VersionAppendService versions;@Autowired RequirementMutationService mutations;
    private static final String PASSWORD="Wave three developer é";
    private record Created(String username,UserData user) {}
    @AfterEach void cleanupContext() { org.springframework.security.test.context.TestSecurityContextHolder.clearContext(); }
    private long adminId() { return ((Number)em.createNativeQuery("SELECT MIN(u.userId) FROM `User` u JOIN `UserRole` ur ON ur.userId=u.userId JOIN `Role` r ON r.roleId=ur.roleId WHERE u.accountStatus='ENABLED' AND r.roleCode='ADMIN'").getSingleResult()).longValue(); }
    private void act(long id) { Actor actor=access.requireEnabledActor(id);SecurityContextHolder.getContext().setAuthentication(UsernamePasswordAuthenticationToken.authenticated(actor,null,List.of())); }
    private Created user(String... roles) { act(adminId());String name="w3_"+UUID.randomUUID().toString().replace("-","");var result=new Created(name,administration.create(name,name+"@example.invalid","Wave three synthetic",PASSWORD,List.of(roles)));org.springframework.security.test.context.TestSecurityContextHolder.clearContext();return result; }
    private MockHttpSession login(Created u)throws Exception { org.springframework.security.test.context.TestSecurityContextHolder.clearContext();var csrf=mvc.perform(get("/api/v1/auth/csrf")).andExpect(status().isOk()).andReturn();var session=(MockHttpSession)csrf.getRequest().getSession(false);mvc.perform(post("/api/v1/auth/login").session(session).header("X-CSRF-TOKEN",read(csrf).get("token").asText()).contentType("application/json").content(json.writeValueAsString(Map.of("login",u.username(),"password",PASSWORD)))).andExpect(status().isOk());return session; }
    private JsonNode read(MvcResult r)throws Exception { return json.readTree(r.getResponse().getContentAsString()); }
    private JsonNode postJson(String path,MockHttpSession s,Object body,int expected)throws Exception { org.springframework.security.test.context.TestSecurityContextHolder.clearContext();String csrf=read(mvc.perform(get("/api/v1/auth/csrf").session(s)).andExpect(status().isOk()).andReturn()).get("token").asText();return read(mvc.perform(post(path).session(s).header("X-CSRF-TOKEN",csrf).contentType("application/json").content(json.writeValueAsString(body))).andExpect(status().is(expected)).andReturn()); }
    private JsonNode patch(String path,MockHttpSession s,Object body,int expected)throws Exception { org.springframework.security.test.context.TestSecurityContextHolder.clearContext();String csrf=read(mvc.perform(get("/api/v1/auth/csrf").session(s)).andExpect(status().isOk()).andReturn()).get("token").asText();return read(mvc.perform(org.springframework.test.web.servlet.request.MockMvcRequestBuilders.patch(path).session(s).header("X-CSRF-TOKEN",csrf).contentType("application/json").content(json.writeValueAsString(body))).andExpect(status().is(expected)).andReturn()); }
    private JsonNode getJson(String path,MockHttpSession s,int expected)throws Exception { org.springframework.security.test.context.TestSecurityContextHolder.clearContext();return read(mvc.perform(get(path).session(s)).andExpect(status().is(expected)).andReturn()); }
    private Map<String,Object> content(String title) { return Map.of("title",title,"description","Explicit observable behavior","level","USER","kind","FUNCTIONAL","priority","HIGH","source","Synthetic stakeholder interview","rationale","Prevent data loss","acceptanceCriteria","Given a valid form, saving returns its saved record with unchanged values."); }
    private JsonNode create(MockHttpSession s)throws Exception { return postJson("/api/v1/requirements",s,content("w3_"+UUID.randomUUID()),201); }
    private String path(JsonNode r) { return "/api/v1/requirements/"+r.get("requirementId").asText(); }
    private JsonNode submit(JsonNode r,MockHttpSession s)throws Exception { return postJson(path(r)+"/submit",s,Map.of("expectedLockVersion",r.get("lockVersion").asText()),201); }
    private JsonNode decision(JsonNode review,MockHttpSession s,String value,String revision,String comment,int expected)throws Exception { Map<String,Object> body=new HashMap<>();body.put("decision",value);body.put("expectedRequirementLockVersion",revision);body.put("comment",comment);return postJson("/api/v1/requirement-reviews/"+review.get("reviewId").asText()+"/decision",s,body,expected); }
    private long count(String table,String where,long id) { return ((Number)em.createNativeQuery("SELECT COUNT(*) FROM `"+table+"` WHERE "+where+"=:id").setParameter("id",id).getSingleResult()).longValue(); }
    private long auditCount(String target,String action,String outcome) { return ((Number)em.createNativeQuery("SELECT COUNT(*) FROM `AuditEvent` WHERE targetId=:id AND action=:action AND outcome=:outcome").setParameter("id",target).setParameter("action",action).setParameter("outcome",outcome).getSingleResult()).longValue(); }

    private JsonNode baseline(MockHttpSession eng,MockHttpSession rev)throws Exception { var r=create(eng);return decision(submit(r,eng),rev,"APPROVE","1",null,200).get("requirement"); }
    private String cp(JsonNode c) { return "/api/v1/changes/"+c.get("changeRequestId").asText(); }
    private JsonNode newChange(JsonNode r,MockHttpSession eng)throws Exception { return postJson(path(r)+"/changes",eng,Map.of("requestTitle","Explicit proposal","reason","Synthetic controlled change reason","expectedRequirementLockVersion",r.get("lockVersion").asText()),201); }
    private JsonNode crSubmit(JsonNode c,MockHttpSession eng)throws Exception { return postJson(cp(c)+"/submit",eng,Map.of("expectedLockVersion",c.get("lockVersion").asText()),201); }
    private JsonNode crDecision(JsonNode round,MockHttpSession rev,String value,String revision,String comment,int expected)throws Exception { var body=new HashMap<String,Object>();body.put("decision",value);body.put("comment",comment);body.put("expectedChangeLockVersion",revision);return postJson("/api/v1/change-reviews/"+round.get("changeReviewId").asText()+"/decision",rev,body,expected); }
    private JsonNode crApply(JsonNode c,JsonNode r,MockHttpSession eng,int expected)throws Exception { return postJson(cp(c)+"/apply",eng,Map.of("expectedRequirementLockVersion",r.get("lockVersion").asText(),"expectedChangeLockVersion",c.get("lockVersion").asText()),expected); }
    private static final List<String> CONTENT=List.of("Title","Description","Level","Kind","Priority","Source","Rationale","AcceptanceCriteria");
    private void snapshotEquals(JsonNode c,JsonNode round) { assertEquals(c.get("baseVersionId"),round.get("snapshotBaseVersionId"));assertEquals(c.get("requestTitle"),round.get("snapshotRequestTitle"));assertEquals(c.get("reason"),round.get("snapshotReason"));for(String field:CONTENT)assertEquals(c.get("proposed"+field),round.get("snapshotProposed"+field)); }
    @Test void formalCreationDraftPresenceStrictInputsAndNumericHistory()throws Exception {
        MockHttpSession eng=login(user("REQUIREMENT_ENGINEER")),rev=login(user("REVIEWER")),viewer=login(user("VIEWER"));var draft=create(eng);
        assertEquals("STATE_CONFLICT",postJson(path(draft)+"/changes",eng,Map.of("requestTitle","Draft has no baseline","reason","reason","expectedRequirementLockVersion","0"),409).get("code").asText());
        var r=baseline(eng,rev);String p=path(r);getJson(p+"/changes?size=101",viewer,400);getJson("/api/v1/requirements/9223372036854775807/changes",viewer,404);
        postJson(p+"/changes",eng,Map.of("requestTitle","Forged base","reason","reason","expectedRequirementLockVersion","2","baseVersionId","1"),400);
        postJson(p+"/changes",eng,Map.of("requestTitle","Numeric revision","reason","reason","expectedRequirementLockVersion",2),400);
        postJson(p+"/changes",viewer,Map.of("requestTitle","Unauthorized","reason","reason","expectedRequirementLockVersion","2"),403);
        var c=newChange(r,eng);assertEquals("DRAFT",c.get("status").asText());assertEquals(r.get("currentVersionId"),c.get("baseVersionId"));assertEquals("0",c.get("lockVersion").asText());assertTrue(c.get("changeRequestId").isTextual());assertFalse(c.has("activeRequirementId"));assertTrue(c.get("appliedBy").isNull());for(String field:CONTENT)assertEquals(r.get(Character.toLowerCase(field.charAt(0))+field.substring(1)),c.get("proposed"+field));
        assertEquals("ACTIVE_CHANGE_EXISTS",postJson(p+"/changes",eng,Map.of("requestTitle","Second active","reason","reason","expectedRequirementLockVersion","2"),409).get("code").asText());
        patch(cp(c),eng,Map.of("expectedLockVersion","0"),400);patch(cp(c),eng,Map.of("baseVersionId","1","expectedLockVersion","0"),400);patch(cp(c),eng,Map.of("status","APPROVED","expectedLockVersion","0"),400);
        var update=new HashMap<String,Object>();update.put("proposedSource",null);update.put("proposedTitle","Independent proposal title");update.put("expectedLockVersion","0");c=patch(cp(c),eng,update,200);assertTrue(c.get("proposedSource").isNull());assertEquals("Independent proposal title",c.get("proposedTitle").asText());assertEquals("INCOMPLETE_CONTENT",postJson(cp(c)+"/submit",eng,Map.of("expectedLockVersion","1"),400).get("code").asText());assertEquals(0,count("ChangeRequestReview","changeRequestId",c.get("changeRequestId").asLong()));
        c=patch(cp(c),eng,Map.of("proposedSource","Restored source","expectedLockVersion","1"),200);assertEquals(r,getJson(p,viewer,200));var list=getJson(p+"/changes?status=DRAFT",viewer,200);assertTrue(list.get("totalElements").isIntegralNumber());assertEquals(1,list.get("items").size());assertEquals(c,getJson(cp(c),viewer,200));assertEquals(1,getJson(p+"/versions",viewer,200).get("items").size());getJson(p+"/changes?status=UNKNOWN",viewer,400);getJson(cp(c)+"/reviews?page=-1",viewer,400);getJson("/api/v1/changes/9223372036854775807/reviews",viewer,404);
    }
    @Test void elevenValueImmutableRoundsAndApprovalDoNotChangeParentOrVersion()throws Exception {
        MockHttpSession eng=login(user("REQUIREMENT_ENGINEER")),rev=login(user("REVIEWER")),viewer=login(user("VIEWER"));var r=baseline(eng,rev);var c=newChange(r,eng);var first=crSubmit(c,eng);snapshotEquals(c,first);assertEquals(1,first.get("roundNo").asInt());assertTrue(first.get("roundNo").isIntegralNumber());assertTrue(first.get("changeReviewId").isTextual());assertTrue(first.get("reviewerId").isNull());assertEquals("PENDING",first.get("reviewStatus").asText());
        patch(cp(c),eng,Map.of("proposedTitle","Frozen","expectedLockVersion","1"),409);postJson(cp(c)+"/cancel",eng,Map.of("expectedLockVersion","1"),409);crDecision(first,rev,"REQUEST_CHANGES","1"," ",400);var returned=crDecision(first,rev,"REQUEST_CHANGES","1","Make every observable field explicit",200).get("change");assertEquals("DRAFT",returned.get("status").asText());
        var fields=new HashMap<String,Object>();fields.put("requestTitle","Second request title");fields.put("reason","Second immutable reason");fields.put("proposedTitle","Changed title");fields.put("proposedDescription","Changed observable description");fields.put("proposedLevel","SYSTEM");fields.put("proposedKind","QUALITY");fields.put("proposedPriority","CRITICAL");fields.put("proposedSource","Changed source");fields.put("proposedRationale","Changed rationale");fields.put("proposedAcceptanceCriteria","When a valid action completes, its full resulting record is displayed.");fields.put("expectedLockVersion","2");c=patch(cp(c),eng,fields,200);var second=crSubmit(c,eng);snapshotEquals(c,second);assertEquals(2,second.get("roundNo").asInt());assertNotEquals(first.get("changeReviewId"),second.get("changeReviewId"));
        var metadata=patch(path(r)+"/metadata",eng,Map.of("tagIds",List.of(),"expectedLockVersion","2"),200);assertEquals("3",metadata.get("lockVersion").asText());var approved=crDecision(second,rev,"APPROVE","4",null,200);assertEquals("APPROVED",approved.get("change").get("status").asText());assertFalse(approved.has("version"));assertEquals(metadata,getJson(path(r),eng,200));assertEquals(1,getJson(path(r)+"/versions",eng,200).get("items").size());
        crDecision(first,rev,"REJECT","5","Completed round cannot be overwritten",409);crDecision(second,rev,"APPROVE","5",null,409);patch(cp(c),eng,Map.of("reason","Cannot edit approval","expectedLockVersion","5"),409);
        var history=getJson(cp(c)+"/reviews",viewer,200);assertTrue(history.get("totalElements").isIntegralNumber());assertEquals(2,history.get("items").size());snapshotEquals(newChangeProjection(first),history.get("items").get(0));assertEquals("REQUEST_CHANGES",history.get("items").get(0).get("decision").asText());assertEquals("Make every observable field explicit",history.get("items").get(0).get("comment").asText());snapshotEquals(c,history.get("items").get(1));assertEquals("APPROVE",history.get("items").get(1).get("decision").asText());
    }
    private JsonNode newChangeProjection(JsonNode round) { var c=json.createObjectNode();c.set("baseVersionId",round.get("snapshotBaseVersionId"));c.set("requestTitle",round.get("snapshotRequestTitle"));c.set("reason",round.get("snapshotReason"));for(String f:CONTENT)c.set("proposed"+f,round.get("snapshotProposed"+f));return c; }
    @Test void proposerUnionRolesLiveRevocationCancelAndRejectTerminal()throws Exception {
        Created proposer=user("ADMIN","REQUIREMENT_ENGINEER","REVIEWER","PROJECT_MEMBER","VIEWER"),submitter=user("REQUIREMENT_ENGINEER"),reviewer=user("REVIEWER"),viewer=user("VIEWER");MockHttpSession own=login(proposer),other=login(submitter),rev=login(reviewer),view=login(viewer);var r=baseline(own,rev);var c=newChange(r,own);postJson(cp(c)+"/cancel",other,Map.of("expectedLockVersion","0"),403);var round=crSubmit(c,other);assertEquals(Long.toString(submitter.user().userId()),round.get("submittedBy").asText());assertEquals("SELF_REVIEW",crDecision(round,own,"APPROVE","1",null,403).get("code").asText());getJson("/api/v1/change-reviews/pending",view,403);crDecision(round,view,"APPROVE","1",null,403);
        postJson("/api/v1/change-reviews/"+round.get("changeReviewId").asText()+"/decision",rev,Map.of("decision","APPROVE","expectedChangeLockVersion","1","expectedRequirementLockVersion","2"),400);crDecision(round,rev,"REJECT","1",null,400);var rejected=crDecision(round,rev,"REJECT","1","Rejected controlled proposal",200).get("change");assertEquals("REJECTED",rejected.get("status").asText());postJson(cp(c)+"/submit",own,Map.of("expectedLockVersion","2"),409);crApply(rejected,r,own,409);
        c=newChange(r,own);var cancelled=postJson(cp(c)+"/cancel",own,Map.of("expectedLockVersion","0"),200);assertEquals("CANCELLED",cancelled.get("status").asText());postJson(cp(c)+"/cancel",own,Map.of("expectedLockVersion","1"),409);c=newChange(r,own);round=crSubmit(c,own);var pending=getJson("/api/v1/change-reviews/pending?size=100",rev,200);assertTrue(pending.get("totalElements").isIntegralNumber());assertEquals("PENDING",getJson(cp(c)+"/reviews",view,200).get("items").get(0).get("reviewStatus").asText());
        act(adminId());administration.roles(Long.toString(reviewer.user().userId()),Map.of("roles",List.of("VIEWER"),"expectedLockVersion","0"));org.springframework.security.test.context.TestSecurityContextHolder.clearContext();crDecision(round,rev,"APPROVE","1",null,403);assertEquals(r,getJson(path(r),own,200));assertEquals(1,getJson(path(r)+"/versions",view,200).get("items").size());assertEquals(3,getJson(path(r)+"/changes",view,200).get("items").size());
    }
    @Test void applyFromVerifiedAndImplementedAppendsConsecutiveVersionsAndResetsApproval()throws Exception {
        Created engineer=user("REQUIREMENT_ENGINEER"),reviewer=user("REVIEWER");MockHttpSession eng=login(engineer),rev=login(reviewer),member=login(user("PROJECT_MEMBER"));var r=baseline(eng,rev);String p=path(r);var v1=getJson(p+"/versions",eng,200).get("items").get(0);
        for(String starting:List.of("VERIFIED","IMPLEMENTED")) {
            r=postJson(p+"/implement",member,Map.of("expectedVersionId",r.get("currentVersionId").asText(),"expectedLockVersion",r.get("lockVersion").asText(),"description","Synthetic implementation confirmation"),200);
            if(starting.equals("VERIFIED"))r=postJson(p+"/verify",member,Map.of("expectedVersionId",r.get("currentVersionId").asText(),"expectedLockVersion",r.get("lockVersion").asText(),"description","Synthetic verification confirmation"),200);
            var c=newChange(r,eng);c=patch(cp(c),eng,Map.of("proposedTitle","Applied title for "+starting,"expectedLockVersion","0"),200);var round=crSubmit(c,eng);c=crDecision(round,rev,"APPROVE","2",null,200).get("change");assertEquals(r,getJson(p,eng,200));assertEquals("LOCK_VERSION_CONFLICT",postJson(cp(c)+"/apply",eng,Map.of("expectedRequirementLockVersion","0","expectedChangeLockVersion","3"),409).get("code").asText());assertEquals("LOCK_VERSION_CONFLICT",postJson(cp(c)+"/apply",eng,Map.of("expectedRequirementLockVersion",r.get("lockVersion").asText(),"expectedChangeLockVersion","0"),409).get("code").asText());
            postJson(cp(c)+"/apply",eng,Map.of("expectedRequirementLockVersion",r.get("lockVersion").asText(),"expectedChangeLockVersion","3","versionNo",22),400);var result=crApply(c,r,eng,200);var v=result.get("version");var after=result.get("requirement");assertEquals(starting.equals("VERIFIED")?2:3,v.get("versionNo").asInt());assertTrue(v.get("versionNo").isIntegralNumber());assertTrue(v.get("initialReviewId").isNull());assertEquals(c.get("changeRequestId"),v.get("appliedChangeRequestId"));assertEquals(Long.toString(engineer.user().userId()),v.get("createdBy").asText());assertEquals(c.get("reason"),v.get("changeReason"));assertEquals("APPROVED",after.get("status").asText());assertEquals(v.get("versionId"),after.get("currentVersionId"));assertEquals("APPLIED",result.get("change").get("status").asText());assertEquals(v.get("createdBy"),result.get("change").get("appliedBy"));assertEquals(v.get("createdAt"),result.get("change").get("appliedAt"));for(String field:CONTENT){String key=Character.toLowerCase(field.charAt(0))+field.substring(1);assertEquals(c.get("proposed"+field),v.get(key));assertEquals(v.get(key),after.get(key));}
            Object[] audit=(Object[])em.createNativeQuery("SELECT CAST(beforeData AS CHAR),CAST(afterData AS CHAR) FROM `AuditEvent` WHERE targetType='CHANGE_REQUEST' AND targetId=:id AND action='CHANGE_APPLY' AND outcome='SUCCESS'").setParameter("id",c.get("changeRequestId").asText()).getSingleResult();var beforeAudit=json.readTree((String)audit[0]);var afterAudit=json.readTree((String)audit[1]);assertEquals(starting,beforeAudit.get("requirementStatus").asText());assertEquals("APPROVED",afterAudit.get("requirementStatus").asText());assertEquals(round.get("changeReviewId"),afterAudit.get("changeReviewId"));assertEquals(v.get("versionId"),afterAudit.get("currentVersionId"));assertEquals(c.get("baseVersionId"),beforeAudit.get("currentVersionId"));crApply(result.get("change"),after,eng,409);assertEquals(v1,getJson(p+"/versions/"+v1.get("versionId").asText(),eng,200));snapshotEquals(c,getJson(cp(c)+"/reviews",eng,200).get("items").get(0));r=after;
        }
        assertEquals(3,getJson(p+"/versions",eng,200).get("items").size());assertEquals(2,getJson(p+"/changes?status=APPLIED",eng,200).get("items").size());
    }
    private RequirementData formal(long engineer,long reviewer) { act(engineer);var r=requirements.create("w3 atomic fixture "+UUID.randomUUID(),"Observable behavior","USER","FUNCTIONAL","HIGH","source","rationale","Saving shows unchanged values").requirement();var round=reviews.submit(Long.toString(r.requirementId()),"0");act(reviewer);return requirementsData(reviews.decide(Long.toString(round.reviewId()),"APPROVE",null,"1").requirement().requirementId(),engineer); }
    private RequirementData requirementsData(long id,long actor) { act(actor);return requirements.read(Long.toString(id)).requirement(); }
    private long connection() { return ((Number)em.createNativeQuery("SELECT CONNECTION_ID()").getSingleResult()).longValue(); }
    @Test void physicalTransactionRollbackAndStaleOwnershipApprovalGuards() {
        Created eng=user("REQUIREMENT_ENGINEER"),rev=user("REVIEWER");var r=formal(eng.user().userId(),rev.user().userId());String parent=Long.toString(r.requirementId());act(eng.user().userId());var c=changes.create(parent,"Atomic proposal","reason","2");Actor engineer=access.requireEnabledActor(eng.user().userId()),reviewer=access.requireEnabledActor(rev.user().userId());String id=Long.toString(c.changeRequestId());long successes=auditCount(id,"CHANGE_APPLY","SUCCESS");
        assertThrows(IllegalStateException.class,()->new TransactionTemplate(manager).executeWithoutResult(status->{long physical=connection();var round=writes.submit(engineer,c.changeRequestId(),"0");assertEquals(physical,connection());assertEquals("PENDING",round.reviewStatus());throw new IllegalStateException("WAVE3_DEVELOPER_SUBMIT_ROLLBACK");}));assertEquals(0,count("ChangeRequestReview","changeRequestId",c.changeRequestId()));assertEquals("DRAFT",changes.read(id).status());assertEquals(0,changes.read(id).lockVersion());
        var round=changes.submit(id,"0");assertThrows(IllegalStateException.class,()->new TransactionTemplate(manager).executeWithoutResult(status->{long physical=connection();var result=writes.decide(reviewer,round.changeReviewId(),"APPROVE",null,"1");assertEquals(physical,connection());assertEquals("APPROVED",result.change().status());throw new IllegalStateException("WAVE3_DEVELOPER_DECISION_ROLLBACK");}));assertEquals("UNDER_REVIEW",changes.read(id).status());assertEquals("PENDING",changes.history(id,0,20).items().getFirst().reviewStatus());act(rev.user().userId());changes.decide(Long.toString(round.changeReviewId()),"APPROVE",null,"1");
        assertThrows(IllegalStateException.class,()->new TransactionTemplate(manager).executeWithoutResult(status->{long physical=connection();var result=writes.apply(engineer,c.changeRequestId(),"2","2");assertEquals(physical,connection());assertEquals(2,result.version().versionNo());assertEquals("APPLIED",result.change().status());assertEquals(successes+1,auditCount(id,"CHANGE_APPLY","SUCCESS"));throw new IllegalStateException("WAVE3_DEVELOPER_APPLY_ROLLBACK");}));act(eng.user().userId());assertEquals("APPROVED",changes.read(id).status());assertNull(changes.read(id).appliedAt());assertEquals(r,requirements.read(parent).requirement());assertEquals(1,count("RequirementVersion","requirementId",r.requirementId()));assertEquals(successes,auditCount(id,"CHANGE_APPLY","SUCCESS"));
        assertThrows(org.springframework.transaction.IllegalTransactionStateException.class,()->versions.appendApplied(r.requirementId(),c.changeRequestId(),r.currentVersionId(),c.proposed(),engineer.userId(),java.time.Instant.now(),"reason"));assertThrows(org.springframework.transaction.IllegalTransactionStateException.class,()->mutations.installAppliedVersion(r.requirementId(),r.currentVersionId(),1,c.proposed(),java.time.Instant.now()));

        new TransactionTemplate(manager).executeWithoutResult(status->{status.setRollbackOnly();em.createNativeQuery("UPDATE `ChangeRequestReview` SET decision='REJECT',comment='Synthetic rejection context' WHERE changeReviewId=:id").setParameter("id",round.changeReviewId()).executeUpdate();em.clear();assertEquals(ErrorCode.STATE_CONFLICT,assertThrows(RmsException.class,()->writes.apply(engineer,c.changeRequestId(),"2","2")).code());});
        act(eng.user().userId());var applied=changes.apply(id,"2","2");assertEquals("APPLIED",applied.change().status());assertEquals(2,count("RequirementVersion","requirementId",r.requirementId()));var next=changes.create(parent,"Second atomic proposal","reason","3");var nextRound=changes.submit(Long.toString(next.changeRequestId()),"0");act(rev.user().userId());changes.decide(Long.toString(nextRound.changeReviewId()),"APPROVE",null,"1");
        new TransactionTemplate(manager).executeWithoutResult(status->{status.setRollbackOnly();em.createNativeQuery("UPDATE `Requirement` SET currentVersionId=:old WHERE requirementId=:id").setParameter("old",r.currentVersionId()).setParameter("id",r.requirementId()).executeUpdate();em.clear();assertEquals(ErrorCode.BASE_VERSION_STALE,assertThrows(RmsException.class,()->writes.apply(engineer,next.changeRequestId(),"3","2")).code());});
        var other=formal(eng.user().userId(),rev.user().userId());
        new TransactionTemplate(manager).executeWithoutResult(status->{status.setRollbackOnly();assertThrows(org.hibernate.exception.ConstraintViolationException.class,()->em.createNativeQuery("UPDATE `ChangeRequest` SET baseVersionId=:other WHERE changeRequestId=:id").setParameter("other",other.currentVersionId()).setParameter("id",next.changeRequestId()).executeUpdate());});
        new TransactionTemplate(manager).executeWithoutResult(status->{status.setRollbackOnly();assertThrows(org.hibernate.exception.ConstraintViolationException.class,()->em.createNativeQuery("UPDATE `Requirement` SET currentVersionId=:other WHERE requirementId=:id").setParameter("other",other.currentVersionId()).setParameter("id",r.requirementId()).executeUpdate());});
        act(eng.user().userId());assertEquals(applied.requirement().currentVersionId(),requirements.read(parent).requirement().currentVersionId());assertEquals("APPROVED",changes.read(Long.toString(next.changeRequestId())).status());assertEquals(2,count("RequirementVersion","requirementId",r.requirementId()));
    }
    @Test void concurrentCreateSubmitDecisionAndApplyHaveOneWinnerNoReplay()throws Exception {
        Created eng=user("REQUIREMENT_ENGINEER"),rev=user("REVIEWER");var r=formal(eng.user().userId(),rev.user().userId());String parent=Long.toString(r.requirementId());assertEquals(List.of("ACTIVE_CHANGE_EXISTS","SUCCESS"),race(eng.user().userId(),()->changes.create(parent,"Concurrent proposal","reason","2")));act(eng.user().userId());var c=changes.list(parent,null,0,20).items().getFirst();String id=Long.toString(c.changeRequestId());assertEquals(1,count("ChangeRequest","requirementId",r.requirementId()));assertEquals(List.of("LOCK_VERSION_CONFLICT","SUCCESS"),race(eng.user().userId(),()->changes.submit(id,"0")));assertEquals(1,count("ChangeRequestReview","changeRequestId",c.changeRequestId()));act(eng.user().userId());var round=changes.history(id,0,20).items().getFirst();String rid=Long.toString(round.changeReviewId());assertEquals(List.of("LOCK_VERSION_CONFLICT","SUCCESS"),race(rev.user().userId(),()->changes.decide(rid,"APPROVE",null,"1")));assertEquals(1,auditCount(rid,"CHANGE_REVIEW_DECISION","SUCCESS"));assertEquals(1,auditCount(rid,"CHANGE_REVIEW_DECISION","FAILED"));assertEquals(List.of("LOCK_VERSION_CONFLICT","SUCCESS"),race(eng.user().userId(),()->changes.apply(id,"2","2")));act(eng.user().userId());assertEquals(2,count("RequirementVersion","requirementId",r.requirementId()));assertEquals(1,count("RequirementVersion","appliedChangeRequestId",c.changeRequestId()));assertEquals(1,auditCount(id,"CHANGE_APPLY","SUCCESS"));assertEquals(1,auditCount(id,"CHANGE_APPLY","FAILED"));assertEquals(3,requirements.read(parent).requirement().lockVersion());assertEquals(3,changes.read(id).lockVersion());
    }
    private List<String> race(long actor,Callable<?> command)throws Exception { var barrier=new CyclicBarrier(2);try(var pool=Executors.newFixedThreadPool(2)){List<Future<String>> futures=new ArrayList<>();for(int i=0;i<2;i++)futures.add(pool.submit(()->{act(actor);try{barrier.await(10,TimeUnit.SECONDS);command.call();return "SUCCESS";}catch(RmsException e){return e.code().name();}finally{SecurityContextHolder.clearContext();}}));List<String> result=new ArrayList<>();for(var f:futures)result.add(f.get(20,TimeUnit.SECONDS));Collections.sort(result);return result;} }
}
