import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { mount, flushPromises } from '@vue/test-utils';
import { createPinia } from 'pinia';
import { createMemoryHistory } from 'vue-router';
import App from '../App.vue';
import { createAppRouter } from '../router';
import { useSession } from '../auth/useSession';
import { api } from '../api/client';
import { business } from '../api/business';
import { ApiFailure } from '../errors/api-error';
import type { ApplyChangeResponse, ChangeRequestResponse, ChangeRequestReviewResponse, RoleCode } from '../api/contracts.generated';
import { proposalCommand, proposalContent } from './change';
import { syntheticChange, syntheticChangeReview, syntheticPage, syntheticRequirement, syntheticTag, syntheticVersion } from './fixtures';
const formal = { ...syntheticRequirement, ...proposalContent(syntheticChange), status: 'VERIFIED' as const, currentVersionId: syntheticVersion.versionId };
const reviewed = { ...syntheticChange, status: 'UNDER_REVIEW' as const };
const changePath = `/changes/${syntheticChange.changeRequestId}`;
const reviewPath = `/change-reviews/${syntheticChangeReview.changeReviewId}?changeRequestId=${syntheticChange.changeRequestId}&requirementId=${syntheticChange.requirementId}`;
beforeEach(() => {
  api.clearCsrf(); vi.spyOn(api, 'refreshCsrf').mockResolvedValue(); vi.spyOn(api, 'session').mockResolvedValue({ user: { userId: '2', displayName: '独立评审者', accountStatus: 'ENABLED' }, roles: ['REVIEWER'] });
  vi.spyOn(business, 'requirement').mockResolvedValue(formal); vi.spyOn(business, 'version').mockResolvedValue(syntheticVersion); vi.spyOn(business, 'versions').mockResolvedValue(syntheticPage([syntheticVersion]));
  vi.spyOn(business, 'change').mockResolvedValue(syntheticChange); vi.spyOn(business, 'changes').mockResolvedValue(syntheticPage([syntheticChange])); vi.spyOn(business, 'changeReviews').mockResolvedValue(syntheticPage([syntheticChangeReview], 100)); vi.spyOn(business, 'pendingChangeReviews').mockResolvedValue(syntheticPage([syntheticChangeReview]));
  vi.spyOn(business, 'tags').mockResolvedValue(syntheticPage([syntheticTag])); vi.spyOn(window, 'confirm').mockReturnValue(true);
});
afterEach(() => vi.restoreAllMocks());
async function workspace(path: string, roles: RoleCode[] = ['REVIEWER'], userId = '2') {
  vi.mocked(api.session).mockResolvedValue({ user: { userId, displayName: '开发账号', accountStatus: 'ENABLED' }, roles });
  const pinia = createPinia(); const router = createAppRouter(pinia, createMemoryHistory()); await router.push(path); await router.isReady(); const wrapper = mount(App, { global: { plugins: [pinia, router] } }); await flushPromises(); return { wrapper, router, pinia };
}
describe('Wave 3 change workspace, immutable rounds and explicit apply developer checks', () => {
  it('lists changes beneath the authorized parent and creates with parent revision then opens server copied draft', async () => {
    const send = vi.spyOn(business, 'createChange').mockResolvedValue(syntheticChange);
    const { wrapper, router } = await workspace(`/requirements/${formal.requirementId}?tab=changes`, ['REQUIREMENT_ENGINEER'], '1');
    expect(business.changes).toHaveBeenCalledWith(formal.requirementId, { page: 0, size: 20 }, undefined); expect(wrapper.find('[data-tab=changes]').attributes('aria-selected')).toBe('true');
    await wrapper.find('.change-create input').setValue('新的申请'); await wrapper.find('.change-create textarea').setValue('申请理由'); await wrapper.find('.change-create').trigger('submit'); await flushPromises();
    expect(send).toHaveBeenCalledWith(formal.requirementId, { requestTitle: '新的申请', reason: '申请理由', expectedRequirementLockVersion: formal.lockVersion }); expect(router.currentRoute.value.path).toBe(changePath); expect(wrapper.text()).toContain(syntheticChange.baseVersionId); expect((wrapper.find('.content-fields input').element as HTMLInputElement).value).toBe(syntheticChange.proposedTitle); wrapper.unmount();
  });
  it('filters with zero-based numeric pagination and keeps ADMIN-only/withdrawn/unversioned parents read-only', async () => {
    const { wrapper } = await workspace(`/requirements/${formal.requirementId}?tab=changes`, ['ADMIN']); expect(wrapper.find('.change-create').exists()).toBe(false);
    await wrapper.find('.requirement-changes select').setValue('APPROVED'); await flushPromises(); expect(business.changes).toHaveBeenLastCalledWith(formal.requirementId, { page: 0, size: 20 }, 'APPROVED'); wrapper.unmount();
    for (const record of [{ ...formal, isWithdrawn: 1 as const }, syntheticRequirement]) { vi.mocked(business.requirement).mockResolvedValue(record); const view = await workspace(`/requirements/${formal.requirementId}?tab=changes`, ['REQUIREMENT_ENGINEER']); expect(view.wrapper.find('.change-create').exists()).toBe(false); view.wrapper.unmount(); }
  });
  it('preserves creation title/reason after409 and only adopts an explicitly refreshed parent revision', async () => {
    const send = vi.spyOn(business, 'createChange').mockRejectedValue(new ApiFailure('LOCK_VERSION_CONFLICT', 'conflict', 409));
    const { wrapper } = await workspace(`/requirements/${formal.requirementId}?tab=changes`, ['REQUIREMENT_ENGINEER']); await wrapper.find('.change-create input').setValue('保留的申请标题'); await wrapper.find('.change-create textarea').setValue('保留的申请理由'); await wrapper.find('.change-create').trigger('submit'); await flushPromises();
    vi.mocked(business.requirement).mockResolvedValue({ ...formal, lockVersion: '9007199254740994' }); await wrapper.find('.error-panel button').trigger('click'); await flushPromises();
    expect((wrapper.find('.change-create input').element as HTMLInputElement).value).toBe('保留的申请标题'); expect((wrapper.find('.change-create textarea').element as HTMLTextAreaElement).value).toBe('保留的申请理由'); expect(send).toHaveBeenCalledTimes(1);
    await wrapper.find('.change-create').trigger('submit'); await flushPromises(); expect(send).toHaveBeenLastCalledWith(formal.requirementId, { requestTitle: '保留的申请标题', reason: '保留的申请理由', expectedRequirementLockVersion: '9007199254740994' }); wrapper.unmount();
  });
  it('saves the full proposal with CR revision and requires saving local edits before submit', async () => {
    const saved = { ...syntheticChange, requestTitle: '新申请标题', reason: '新理由', proposedTitle: '新建议标题', lockVersion: '9007199254740994' }; const send = vi.spyOn(business, 'editChange').mockResolvedValue(saved); const submit = vi.spyOn(business, 'submitChange').mockResolvedValue(syntheticChangeReview);
    const { wrapper } = await workspace(changePath, ['REQUIREMENT_ENGINEER'], '1'); await wrapper.find('.change-draft input').setValue(saved.requestTitle); await wrapper.find('.change-draft textarea').setValue(saved.reason); await wrapper.find('.content-fields input').setValue(saved.proposedTitle);
    expect(wrapper.findAll('button').find(item => item.text() === '提交变更评审')!.attributes('disabled')).toBeDefined(); await wrapper.find('.change-draft').trigger('submit'); await flushPromises();
    expect(send).toHaveBeenCalledWith(syntheticChange.changeRequestId, syntheticChange.requirementId, { requestTitle: saved.requestTitle, reason: saved.reason, ...proposalCommand(proposalContent(saved)), expectedLockVersion: syntheticChange.lockVersion }); expect(wrapper.text()).toContain('变更草稿已保存'); expect(submit).not.toHaveBeenCalled(); wrapper.unmount();
  });
  it('preserves suggestion fields on409 then uses the refreshed CR revision without automatic replay', async () => {
    const send = vi.spyOn(business, 'editChange').mockRejectedValueOnce(new ApiFailure('LOCK_VERSION_CONFLICT', 'conflict', 409)).mockResolvedValueOnce({ ...syntheticChange, proposedTitle: '保留的建议', lockVersion: '9007199254740995' });
    const { wrapper } = await workspace(changePath, ['REQUIREMENT_ENGINEER'], '1'); await wrapper.find('.content-fields input').setValue('保留的建议'); await wrapper.find('.change-draft').trigger('submit'); await flushPromises();
    vi.mocked(business.change).mockResolvedValue({ ...syntheticChange, proposedTitle: '服务器建议', lockVersion: '9007199254740994' }); await wrapper.find('.error-panel button').trigger('click'); await flushPromises(); expect((wrapper.find('.content-fields input').element as HTMLInputElement).value).toBe('保留的建议'); expect(send).toHaveBeenCalledTimes(1);
    await wrapper.find('.change-draft').trigger('submit'); await flushPromises(); expect(send).toHaveBeenLastCalledWith(syntheticChange.changeRequestId, syntheticChange.requirementId, expect.objectContaining({ proposedTitle: '保留的建议', expectedLockVersion: '9007199254740994' })); wrapper.unmount();
  });
  it('submits a complete saved CR, consumes its snapshot and refreshes to locked UNDER_REVIEW', async () => {
    const send = vi.spyOn(business, 'submitChange').mockImplementation(async () => { vi.mocked(business.change).mockResolvedValue(reviewed); return syntheticChangeReview; }); const { wrapper } = await workspace(changePath, ['REQUIREMENT_ENGINEER'], '1');
    await wrapper.findAll('button').find(item => item.text() === '提交变更评审')!.trigger('click'); await flushPromises(); expect(send).toHaveBeenCalledWith(syntheticChange.changeRequestId, syntheticChange.requirementId, { expectedLockVersion: syntheticChange.lockVersion }); expect(wrapper.text()).toContain('UNDER_REVIEW'); expect(wrapper.find('.change-draft').exists()).toBe(false); wrapper.unmount();
    vi.mocked(business.change).mockResolvedValue({ ...syntheticChange, proposedAcceptanceCriteria: null }); const incomplete = await workspace(changePath, ['REQUIREMENT_ENGINEER']); expect(incomplete.wrapper.findAll('button').find(item => item.text() === '提交变更评审')!.attributes('disabled')).toBeDefined(); incomplete.wrapper.unmount();
  });
  it('limits DRAFT cancellation to engineer plus actual proposer, including role unions', async () => {
    const send = vi.spyOn(business, 'cancelChange').mockImplementation(async () => { const result = { ...syntheticChange, status: 'CANCELLED' as const }; vi.mocked(business.change).mockResolvedValue(result); return result; });
    const { wrapper } = await workspace(changePath, ['REQUIREMENT_ENGINEER'], '1'); await wrapper.findAll('button').find(item => item.text() === '取消本人草稿变更')!.trigger('click'); await flushPromises(); expect(send).toHaveBeenCalledWith(syntheticChange.changeRequestId, syntheticChange.requirementId, { expectedLockVersion: syntheticChange.lockVersion }); expect(wrapper.text()).toContain('CANCELLED 为终态'); expect(wrapper.find('.change-draft').exists()).toBe(false); wrapper.unmount();
    vi.mocked(business.change).mockResolvedValue(syntheticChange); for (const [roles, id] of [[['ADMIN', 'REVIEWER'], '1'], [['ADMIN', 'REQUIREMENT_ENGINEER', 'REVIEWER'], '2']] as [RoleCode[], string][]) { const view = await workspace(changePath, roles, id); expect(view.wrapper.text()).not.toContain('取消本人草稿变更'); view.wrapper.unmount(); }
  });
  it('displays all eleven immutable snapshot fields despite current CR proposal edits', async () => {
    vi.mocked(business.change).mockResolvedValue({ ...reviewed, requestTitle: '当前申请标题', reason: '当前申请理由', proposedTitle: '当前建议标题' }); const { wrapper } = await workspace(reviewPath);
    for (const value of [syntheticChangeReview.snapshotBaseVersionId, syntheticChangeReview.snapshotRequestTitle, syntheticChangeReview.snapshotReason, syntheticChangeReview.snapshotProposedTitle, syntheticChangeReview.snapshotProposedDescription, syntheticChangeReview.snapshotProposedLevel, syntheticChangeReview.snapshotProposedKind, syntheticChangeReview.snapshotProposedPriority, syntheticChangeReview.snapshotProposedSource, syntheticChangeReview.snapshotProposedRationale, syntheticChangeReview.snapshotProposedAcceptanceCriteria]) expect(wrapper.text()).toContain(value);
    expect(wrapper.text()).not.toContain('当前申请标题'); expect(wrapper.text()).not.toContain('当前建议标题'); expect(wrapper.find('.change-decision').exists()).toBe(true); expect(business.changeReviews).toHaveBeenCalledWith(syntheticChange.changeRequestId, syntheticChange.requirementId, { page: 0, size: 100 }); wrapper.unmount();
  });
  it('excludes CR proposer despite multiple roles and different submitter but permits a different requirement creator', async () => {
    vi.mocked(business.change).mockResolvedValue(reviewed); const own = await workspace(reviewPath, ['ADMIN', 'REQUIREMENT_ENGINEER', 'REVIEWER'], '1'); expect(own.wrapper.text()).toContain('不能评审自己提出的变更'); expect(own.wrapper.find('form').exists()).toBe(false); own.wrapper.unmount();
    vi.mocked(business.change).mockResolvedValue({ ...reviewed, createdBy: '3' }); const requirementCreator = await workspace(reviewPath, ['REVIEWER'], '1'); expect(requirementCreator.wrapper.find('.change-decision').exists()).toBe(true); requirementCreator.wrapper.unmount();
  });
  it('preserves review decision/comment on409, reloads CR revision and returns REQUEST_CHANGES with old round retained', async () => {
    vi.mocked(business.change).mockResolvedValue(reviewed); const completed = { ...syntheticChangeReview, reviewStatus: 'COMPLETED' as const, decision: 'REQUEST_CHANGES' as const, reviewerId: '2', comment: '保留的变更意见', decidedAt: '2026-10-03T04:00:00Z' };
    const send = vi.spyOn(business, 'decideChangeReview').mockRejectedValueOnce(new ApiFailure('LOCK_VERSION_CONFLICT', 'conflict', 409)).mockImplementationOnce(async () => { const change = { ...syntheticChange, lockVersion: '9007199254740995' }; vi.mocked(business.change).mockResolvedValue(change); vi.mocked(business.changeReviews).mockResolvedValue(syntheticPage([completed], 100)); return { review: completed, change }; });
    const { wrapper } = await workspace(reviewPath); await wrapper.find('select').setValue('REQUEST_CHANGES'); await wrapper.find('textarea').setValue(completed.comment); await wrapper.find('form').trigger('submit'); await flushPromises(); vi.mocked(business.change).mockResolvedValue({ ...reviewed, lockVersion: '9007199254740994' }); await wrapper.find('.error-panel button').trigger('click'); await flushPromises();
    expect((wrapper.find('textarea').element as HTMLTextAreaElement).value).toBe(completed.comment); expect((wrapper.find('select').element as HTMLSelectElement).value).toBe('REQUEST_CHANGES'); expect(send).toHaveBeenCalledTimes(1); await wrapper.find('form').trigger('submit'); await flushPromises();
    expect(send).toHaveBeenLastCalledWith(syntheticChangeReview.changeReviewId, syntheticChange.changeRequestId, syntheticChange.requirementId, { decision: 'REQUEST_CHANGES', comment: completed.comment, expectedChangeLockVersion: '9007199254740994' }); expect(wrapper.text()).toContain('已完成决策：REQUEST_CHANGES'); expect(wrapper.find('form').exists()).toBe(false); wrapper.unmount();
  });
  it('approves without applying or creating a version and makes completed rounds read-only', async () => {
    vi.mocked(business.change).mockResolvedValue(reviewed); const apply = vi.spyOn(business, 'applyChange'); const completed = { ...syntheticChangeReview, reviewStatus: 'COMPLETED' as const, decision: 'APPROVE' as const, reviewerId: '2', decidedAt: '2026-10-03T04:00:00Z' };
    const send = vi.spyOn(business, 'decideChangeReview').mockImplementation(async () => { const change = { ...syntheticChange, status: 'APPROVED' as const }; vi.mocked(business.change).mockResolvedValue(change); vi.mocked(business.changeReviews).mockResolvedValue(syntheticPage([completed], 100)); return { review: completed, change }; });
    const { wrapper } = await workspace(reviewPath); await wrapper.find('form').trigger('submit'); await flushPromises(); expect(send).toHaveBeenCalledWith(syntheticChangeReview.changeReviewId, syntheticChange.changeRequestId, syntheticChange.requirementId, { decision: 'APPROVE', comment: null, expectedChangeLockVersion: syntheticChange.lockVersion }); expect(apply).not.toHaveBeenCalled(); expect(wrapper.text()).toContain('本轮批准只完成评审'); expect(wrapper.find('form').exists()).toBe(false); wrapper.unmount();
    const viewer = await workspace(reviewPath, ['VIEWER']); expect(viewer.wrapper.text()).toContain('已完成决策：APPROVE'); expect(viewer.wrapper.find('form').exists()).toBe(false); viewer.wrapper.unmount();
  });
  it('keeps old rounds after a returned draft is edited and resubmitted as round two', async () => {
    const old: ChangeRequestReviewResponse = { ...syntheticChangeReview, reviewStatus: 'COMPLETED', decision: 'REQUEST_CHANGES', comment: '旧轮意见', reviewerId: '2', decidedAt: '2026-10-03T04:00:00Z' }; const next: ChangeRequestReviewResponse = { ...syntheticChangeReview, changeReviewId: '9007199254741001', roundNo: 2, snapshotProposedTitle: '重提建议' }; vi.mocked(business.change).mockResolvedValue({ ...syntheticChange, proposedTitle: '重提建议' }); vi.mocked(business.changeReviews).mockResolvedValue(syntheticPage([old], 100));
    vi.spyOn(business, 'submitChange').mockImplementation(async () => { vi.mocked(business.change).mockResolvedValue({ ...reviewed, proposedTitle: '重提建议' }); vi.mocked(business.changeReviews).mockResolvedValue(syntheticPage([old, next], 100)); return next; });
    const { wrapper } = await workspace(changePath, ['REQUIREMENT_ENGINEER'], '1'); await wrapper.findAll('button').find(item => item.text() === '提交变更评审')!.trigger('click'); await flushPromises(); expect(wrapper.text()).toContain('第 1 轮'); expect(wrapper.text()).toContain('第 2 轮'); expect(wrapper.text()).toContain('REQUEST_CHANGES'); expect(wrapper.findAll('a').some(link => link.attributes('href') === reviewPath)).toBe(true); wrapper.unmount();
  });
  it('shows explicit apply for approved current base, consumes actual V2 and refreshes parent to APPROVED', async () => {
    vi.mocked(business.change).mockResolvedValue({ ...syntheticChange, status: 'APPROVED' }); const version = { ...syntheticVersion, ...proposalContent(syntheticChange), source: syntheticChange.proposedSource!, rationale: syntheticChange.proposedRationale!, acceptanceCriteria: syntheticChange.proposedAcceptanceCriteria!, versionId: '9007199254741000', versionNo: 2, initialReviewId: null, appliedChangeRequestId: syntheticChange.changeRequestId };
    const result: ApplyChangeResponse = { change: { ...syntheticChange, status: 'APPLIED', appliedBy: '1', appliedAt: '2026-10-03T05:00:00Z', lockVersion: '9007199254740994' }, requirement: { ...formal, status: 'APPROVED', currentVersionId: version.versionId, lockVersion: '9007199254740994' }, version };
    const send = vi.spyOn(business, 'applyChange').mockImplementation(async () => { vi.mocked(business.change).mockResolvedValue(result.change); vi.mocked(business.requirement).mockResolvedValue(result.requirement); vi.mocked(business.versions).mockResolvedValue(syntheticPage([version], 100)); return result; }); const { wrapper } = await workspace(changePath, ['REQUIREMENT_ENGINEER'], '1');
    expect(wrapper.text()).toContain('尚未改变需求或创建新版本'); await wrapper.find('.change-apply button').trigger('click'); await flushPromises(); expect(send).toHaveBeenCalledWith(syntheticChange.changeRequestId, syntheticChange.requirementId, { expectedRequirementLockVersion: formal.lockVersion, expectedChangeLockVersion: syntheticChange.lockVersion }); expect(wrapper.text()).toContain('已产生正式 V2'); expect(wrapper.text()).toContain('APPLIED 为终态'); expect(wrapper.text()).toContain(result.requirement.currentVersionId); expect(wrapper.text()).toContain('需对新的正式版本进行实现与验证'); expect(wrapper.find('.change-apply button').exists()).toBe(false); wrapper.unmount();
  });
  it('prohibits stale-base/terminal apply and preserves REJECTED/CANCELLED/APPLIED readonly state', async () => {
    vi.mocked(business.change).mockResolvedValue({ ...syntheticChange, status: 'APPROVED' }); vi.mocked(business.requirement).mockResolvedValue({ ...formal, currentVersionId: '9007199254741000' }); const stale = await workspace(changePath, ['REQUIREMENT_ENGINEER'], '1'); expect(stale.wrapper.text()).toContain('基准版本已过期'); expect(stale.wrapper.find('.change-apply button').exists()).toBe(false); stale.wrapper.unmount();
    for (const status of ['REJECTED', 'CANCELLED', 'APPLIED'] as const) { vi.mocked(business.change).mockResolvedValue({ ...syntheticChange, status }); vi.mocked(business.versions).mockResolvedValue(syntheticPage([{ ...syntheticVersion, initialReviewId: null, appliedChangeRequestId: syntheticChange.changeRequestId }], 100)); const view = await workspace(changePath, ['REQUIREMENT_ENGINEER'], '1'); expect(view.wrapper.find('.change-draft').exists()).toBe(false); expect(view.wrapper.find('.change-apply button').exists()).toBe(false); expect(view.wrapper.text()).not.toContain('提交变更评审'); view.wrapper.unmount(); }
  });
  it('preserves decision draft and blocks unknown write replay until explicit reads', async () => {
    vi.mocked(business.change).mockResolvedValue(reviewed); const send = vi.spyOn(business, 'decideChangeReview').mockRejectedValue(new ApiFailure('INTERNAL_ERROR', 'server', 500, undefined, undefined, true)); const { wrapper } = await workspace(reviewPath); await wrapper.find('textarea').setValue('待核对的意见'); await wrapper.find('form').trigger('submit'); await flushPromises(); await wrapper.find('form').trigger('submit'); await flushPromises(); expect(send).toHaveBeenCalledTimes(1); await wrapper.find('.error-panel button').trigger('click'); await flushPromises(); expect(send).toHaveBeenCalledTimes(1); expect((wrapper.find('textarea').element as HTMLTextAreaElement).value).toBe('待核对的意见'); wrapper.unmount();
  });
  it('rechecks actual engineer/reviewer roles before mutation', async () => {
    const edit = vi.spyOn(business, 'editChange'); const { wrapper } = await workspace(changePath, ['REQUIREMENT_ENGINEER'], '1'); vi.mocked(api.session).mockResolvedValue({ user: { userId: '1', displayName: '角色已撤销', accountStatus: 'ENABLED' }, roles: ['VIEWER'] }); await wrapper.find('.change-draft').trigger('submit'); await flushPromises(); expect(edit).not.toHaveBeenCalled(); expect(wrapper.find('.change-draft').exists()).toBe(false); wrapper.unmount();
    vi.mocked(business.change).mockResolvedValue(reviewed); const send = vi.spyOn(business, 'decideChangeReview'); const view = await workspace(reviewPath); vi.mocked(api.session).mockResolvedValue({ user: { userId: '2', displayName: '角色已撤销', accountStatus: 'ENABLED' }, roles: ['VIEWER'] }); await view.wrapper.find('form').trigger('submit'); await flushPromises(); expect(send).not.toHaveBeenCalled(); expect(view.wrapper.find('form').exists()).toBe(false); view.wrapper.unmount();
  });
  it('links the reviewer pending queue with both parent IDs and requires deep-link context', async () => {
    const { wrapper } = await workspace('/change-reviews'); expect(business.pendingChangeReviews).toHaveBeenCalledWith({ page: 0, size: 20 }); expect(wrapper.findAll('a').some(link => link.attributes('href') === reviewPath)).toBe(true); wrapper.unmount(); const viewer = await workspace('/change-reviews', ['VIEWER']); expect(viewer.router.currentRoute.value.path).toBe('/forbidden'); viewer.wrapper.unmount();
    vi.mocked(business.change).mockClear(); const missing = await workspace(`/change-reviews/${syntheticChangeReview.changeReviewId}`, ['VIEWER']); expect(business.change).not.toHaveBeenCalled(); expect(missing.wrapper.text()).toContain('changeRequestId 与 requirementId 上下文'); missing.wrapper.unmount();
  });
  it('discards older context reads and pending edit results after changing CR routes', async () => {
    vi.mocked(business.changeReviews).mockImplementation(async (id, _requirementId, page) => syntheticPage([{ ...syntheticChangeReview, changeRequestId: id }], page.size));
    let finish!: (value: ChangeRequestResponse) => void; vi.mocked(business.change).mockImplementationOnce(() => new Promise(resolve => { finish = resolve; })).mockResolvedValue({ ...syntheticChange, changeRequestId: '2', requestTitle: '第二个申请' }); const first = await workspace(changePath, ['VIEWER']); await first.router.push('/changes/2'); await flushPromises(); finish(syntheticChange); await flushPromises(); expect(first.wrapper.find('h2').text()).toBe('第二个申请'); first.wrapper.unmount();
    vi.mocked(business.change).mockResolvedValue(syntheticChange); let finishSave!: (value: ChangeRequestResponse) => void; vi.spyOn(business, 'editChange').mockImplementation(() => new Promise(resolve => { finishSave = resolve; })); const edit = await workspace(changePath, ['REQUIREMENT_ENGINEER'], '1'); await edit.wrapper.find('.content-fields input').setValue('第一项修改'); await edit.wrapper.find('.change-draft').trigger('submit'); await flushPromises(); vi.mocked(business.change).mockResolvedValue({ ...syntheticChange, changeRequestId: '2', proposedTitle: '第二项建议' }); await edit.router.push('/changes/2'); await flushPromises(); finishSave({ ...syntheticChange, proposedTitle: '迟到的保存结果' }); await flushPromises(); expect((edit.wrapper.find('.content-fields input').element as HTMLInputElement).value).toBe('第二项建议'); expect(edit.wrapper.text()).not.toContain('变更草稿已保存'); edit.wrapper.unmount();
  });
  it('discards an unmounted change read and clears local proposal drafts when session is reset', async () => {
    const { wrapper, pinia } = await workspace(changePath, ['REQUIREMENT_ENGINEER'], '1'); await wrapper.find('.content-fields input').setValue('会话中的本地草稿'); useSession(pinia).reset(); await flushPromises(); expect(wrapper.text()).not.toContain('会话中的本地草稿'); wrapper.unmount();
    let finish!: (value: ChangeRequestResponse) => void; vi.mocked(business.change).mockImplementationOnce(() => new Promise(resolve => { finish = resolve; })); const view = await workspace(changePath, ['VIEWER']); view.wrapper.unmount(); finish(syntheticChange); await flushPromises(); expect(view.wrapper.text()).not.toContain(syntheticChange.requestTitle);
  });
  it('keeps a rejected completed round and reason read-only while CR is a terminal state', async () => {
    vi.mocked(business.change).mockResolvedValue({ ...syntheticChange, status: 'REJECTED' }); vi.mocked(business.changeReviews).mockResolvedValue(syntheticPage([{ ...syntheticChangeReview, reviewStatus: 'COMPLETED', decision: 'REJECT', comment: '保留的拒绝意见', reviewerId: '2', decidedAt: '2026-10-03T04:00:00Z' }], 100));
    const { wrapper } = await workspace(reviewPath, ['VIEWER']); expect(wrapper.text()).toContain('已完成决策：REJECT'); expect(wrapper.text()).toContain('保留的拒绝意见'); expect(wrapper.find('form').exists()).toBe(false); wrapper.unmount();
  });
  it('blocks apply replay after an unknown outcome and requires explicit fresh aggregate reads', async () => {
    vi.mocked(business.change).mockResolvedValue({ ...syntheticChange, status: 'APPROVED' }); const send = vi.spyOn(business, 'applyChange').mockRejectedValue(new ApiFailure('INTERNAL_ERROR', 'server', 500, undefined, undefined, true));
    const { wrapper } = await workspace(changePath, ['REQUIREMENT_ENGINEER'], '1'); await wrapper.find('.change-apply button').trigger('click'); await flushPromises(); await wrapper.find('.change-apply button').trigger('click'); await flushPromises(); expect(send).toHaveBeenCalledTimes(1); expect(wrapper.text()).toContain('提交结果尚未确认');
    await wrapper.find('.change-apply .error-panel button').trigger('click'); await flushPromises(); expect(send).toHaveBeenCalledTimes(1); expect(business.change).toHaveBeenCalledTimes(2); expect(business.requirement).toHaveBeenCalledTimes(2); wrapper.unmount();
  });
  it('requires new implement and verify confirmations against the applied formal V2 ID', async () => {
    const versionId = '9007199254741000'; const appliedParent = { ...formal, status: 'APPROVED' as const, currentVersionId: versionId, lockVersion: '9007199254740994' }; vi.mocked(business.requirement).mockResolvedValue(appliedParent);
    const send = vi.spyOn(business, 'confirmVersion').mockResolvedValueOnce({ ...appliedParent, status: 'IMPLEMENTED', lockVersion: '9007199254740995' }).mockResolvedValueOnce({ ...appliedParent, status: 'VERIFIED', lockVersion: '9007199254740996' });
    const { wrapper } = await workspace(`/requirements/${formal.requirementId}`, ['PROJECT_MEMBER']); await wrapper.find('.lifecycle-actions textarea').setValue('V2 实现结果'); await wrapper.find('.lifecycle-actions form').trigger('submit'); await flushPromises(); expect(send).toHaveBeenCalledWith(formal.requirementId, 'implement', { expectedVersionId: versionId, expectedLockVersion: appliedParent.lockVersion, description: 'V2 实现结果' });
    await wrapper.find('.lifecycle-actions textarea').setValue('V2 验证结果'); await wrapper.find('.lifecycle-actions form').trigger('submit'); await flushPromises(); expect(send).toHaveBeenLastCalledWith(formal.requirementId, 'verify', { expectedVersionId: versionId, expectedLockVersion: '9007199254740995', description: 'V2 验证结果' }); expect(wrapper.text()).toContain('VERIFIED'); wrapper.unmount();
  });
});
