import type { ChangeRequestResponse, ChangeRequestReviewResponse, CreateRequirementRequest, EditChangeRequest, RequirementResponse } from '../api/contracts.generated';
import type { useSession } from '../auth/useSession';
export const CHANGE_STATUSES = ['DRAFT', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'APPLIED', 'CANCELLED'] as const;
export function proposalContent(change: ChangeRequestResponse): CreateRequirementRequest { return { title: change.proposedTitle, description: change.proposedDescription, level: change.proposedLevel, kind: change.proposedKind, priority: change.proposedPriority, source: change.proposedSource, rationale: change.proposedRationale, acceptanceCriteria: change.proposedAcceptanceCriteria }; }
export function proposalCommand(content: CreateRequirementRequest): Omit<EditChangeRequest, 'expectedLockVersion'> { return { proposedTitle: content.title, proposedDescription: content.description, proposedLevel: content.level, proposedKind: content.kind, proposedPriority: content.priority, proposedSource: content.source, proposedRationale: content.rationale, proposedAcceptanceCriteria: content.acceptanceCriteria }; }
export function changeSnapshot(review: ChangeRequestReviewResponse): CreateRequirementRequest { return { title: review.snapshotProposedTitle, description: review.snapshotProposedDescription, level: review.snapshotProposedLevel, kind: review.snapshotProposedKind, priority: review.snapshotProposedPriority, source: review.snapshotProposedSource, rationale: review.snapshotProposedRationale, acceptanceCriteria: review.snapshotProposedAcceptanceCriteria }; }
export function completeChange(change: ChangeRequestResponse): boolean { return [change.requestTitle, change.reason, ...Object.values(proposalContent(change))].every(value => typeof value === 'string' && /\S/u.test(value)); }
export function changeParentAllowed(parent: RequirementResponse): boolean { return parent.isWithdrawn === 0 && !!parent.currentVersionId && ['APPROVED', 'IMPLEMENTED', 'VERIFIED'].includes(parent.status); }
export function canEditChange(session: ReturnType<typeof useSession>, parent: RequirementResponse, change: ChangeRequestResponse): boolean { return session.hasAnyRole(['REQUIREMENT_ENGINEER']) && parent.isWithdrawn === 0 && change.requirementId === parent.requirementId && change.status === 'DRAFT'; }
export function canCancelChange(session: ReturnType<typeof useSession>, parent: RequirementResponse, change: ChangeRequestResponse): boolean { return canEditChange(session, parent, change) && change.createdBy === session.identity?.user.userId; }
export function canApplyChange(session: ReturnType<typeof useSession>, parent: RequirementResponse, change: ChangeRequestResponse): boolean { return session.hasAnyRole(['REQUIREMENT_ENGINEER']) && changeParentAllowed(parent) && change.requirementId === parent.requirementId && change.status === 'APPROVED' && change.baseVersionId === parent.currentVersionId; }
export function canDecideChange(session: ReturnType<typeof useSession>, parent: RequirementResponse, change: ChangeRequestResponse, review: ChangeRequestReviewResponse): boolean { return session.hasAnyRole(['REVIEWER']) && parent.isWithdrawn === 0 && change.status === 'UNDER_REVIEW' && review.reviewStatus === 'PENDING' && review.changeRequestId === change.changeRequestId && review.requirementId === parent.requirementId && change.requirementId === parent.requirementId && review.snapshotBaseVersionId === change.baseVersionId && change.createdBy !== session.identity?.user.userId; }
