// Synthetic developer-check fixtures. No deployment credentials or acceptance oracle inputs.
import type { AdminUserResponse, AuditResponse, ChangeRequestResponse, ChangeRequestReviewResponse, CommentResponse, RequirementRelationResponse, RequirementResponse, RequirementReviewResponse, RequirementVersionResponse, TagResponse, TraceResponse } from '../api/contracts.generated';
export const syntheticTag: TagResponse = { tagId: '9007199254740993', name: '共享标签', description: null, createdBy: '1', createdAt: '2026-10-03T00:00:00Z' };
export const syntheticRequirement: RequirementResponse = { requirementId: '9007199254740994', requirementKey: 'REQ-DEV', title: '开发自检需求', description: '普通纯文本', level: 'SYSTEM', kind: 'FUNCTIONAL', priority: 'MEDIUM', source: null, rationale: null, acceptanceCriteria: null, status: 'DRAFT', creatorId: '1', assigneeId: null, currentVersionId: null, firstSubmittedAt: null, isWithdrawn: 0, withdrawnBy: null, withdrawnAt: null, createdAt: '2026-10-03T00:00:00Z', updatedAt: '2026-10-03T00:00:00Z', lockVersion: '9007199254740993', creator: { userId: '1', displayName: '开发用户', accountStatus: 'ENABLED' }, assignee: null, tags: [syntheticTag] };
export const syntheticUser: AdminUserResponse = { userId: '1', username: 'synthetic-user', email: 'synthetic@example.test', displayName: '开发用户', accountStatus: 'ENABLED', createdAt: '2026-10-03T00:00:00Z', updatedAt: '2026-10-03T00:00:00Z', lockVersion: '9007199254740993', roles: ['ADMIN', 'REQUIREMENT_ENGINEER'], assignments: [{ userId: '1', roleId: '1', grantedBy: '1', grantedAt: '2026-10-03T00:00:00Z' }] };
export const syntheticComment: CommentResponse = { commentId: '9007199254740995', requirementId: syntheticRequirement.requirementId, authorId: '1', content: '<b>纯文本</b>', createdAt: '2026-10-03T00:00:00Z', isDeleted: 0, deletedBy: null, deletedAt: null };
export const syntheticPage = <T>(items: T[], size = 20) => ({ items, page: 0, size, totalElements: items.length });
export const syntheticReview: RequirementReviewResponse = { reviewId: '9007199254740996', requirementId: syntheticRequirement.requirementId, roundNo: 1, snapshotTitle: '冻结的提交标题', snapshotDescription: '冻结的提交描述', snapshotLevel: 'SYSTEM', snapshotKind: 'FUNCTIONAL', snapshotPriority: 'MEDIUM', snapshotSource: '需求输入', snapshotRationale: '改善流程', snapshotAcceptanceCriteria: '按步骤完成后记录结果', submittedBy: '2', submittedAt: '2026-10-03T00:00:00Z', reviewStatus: 'PENDING', reviewerId: null, decision: null, comment: null, decidedAt: null };
export const syntheticVersion: RequirementVersionResponse = { versionId: '9007199254740997', requirementId: syntheticRequirement.requirementId, versionNo: 1, title: syntheticReview.snapshotTitle, description: syntheticReview.snapshotDescription, level: 'SYSTEM', kind: 'FUNCTIONAL', priority: 'MEDIUM', source: syntheticReview.snapshotSource, rationale: syntheticReview.snapshotRationale, acceptanceCriteria: syntheticReview.snapshotAcceptanceCriteria, initialReviewId: syntheticReview.reviewId, appliedChangeRequestId: null, createdBy: '2', createdAt: '2026-10-03T01:00:00Z', changeReason: '首次批准' };
export const syntheticChange: ChangeRequestResponse = { changeRequestId: '9007199254740998', requirementId: syntheticRequirement.requirementId, baseVersionId: syntheticVersion.versionId, requestTitle: '开发变更申请', reason: '补充业务场景', proposedTitle: '建议标题', proposedDescription: '建议描述', proposedLevel: 'USER', proposedKind: 'QUALITY', proposedPriority: 'HIGH', proposedSource: '建议来源', proposedRationale: '建议理由', proposedAcceptanceCriteria: '建议的步骤和结果', status: 'DRAFT', createdBy: '1', createdAt: '2026-10-03T02:00:00Z', updatedAt: '2026-10-03T02:00:00Z', appliedBy: null, appliedAt: null, lockVersion: '9007199254740993' };
export const syntheticChangeReview: ChangeRequestReviewResponse = { changeReviewId: '9007199254740999', requirementId: syntheticChange.requirementId, changeRequestId: syntheticChange.changeRequestId, roundNo: 1, snapshotBaseVersionId: syntheticChange.baseVersionId, snapshotRequestTitle: syntheticChange.requestTitle, snapshotReason: syntheticChange.reason, snapshotProposedTitle: syntheticChange.proposedTitle, snapshotProposedDescription: syntheticChange.proposedDescription, snapshotProposedLevel: syntheticChange.proposedLevel, snapshotProposedKind: syntheticChange.proposedKind, snapshotProposedPriority: syntheticChange.proposedPriority, snapshotProposedSource: syntheticChange.proposedSource!, snapshotProposedRationale: syntheticChange.proposedRationale!, snapshotProposedAcceptanceCriteria: syntheticChange.proposedAcceptanceCriteria!, submittedBy: '3', submittedAt: '2026-10-03T03:00:00Z', reviewStatus: 'PENDING', reviewerId: null, decision: null, comment: null, decidedAt: null };
export const syntheticOther: RequirementResponse = { ...syntheticRequirement, requirementId: '2', requirementKey: 'REQ-OTHER', title: '对端需求', tags: [], lockVersion: '8' };
export const syntheticRelation: RequirementRelationResponse = { relationId: '9007199254741002', sourceRequirementId: syntheticRequirement.requirementId, targetRequirementId: syntheticOther.requirementId, relationType: 'DEPENDS_ON', description: '依赖说明', createdBy: '1', createdAt: '2026-10-03T06:00:00Z' };
export const syntheticTrace: TraceResponse = { rootRequirementId: syntheticRequirement.requirementId, nodes: [syntheticRequirement, syntheticOther], edges: [syntheticRelation], depth: 2, truncated: false };
export const syntheticAudit: AuditResponse = { auditId: '9007199254741003', actorId: '1', requirementId: syntheticRequirement.requirementId, targetType: 'REQUIREMENT', targetId: syntheticRequirement.requirementId, action: 'UPDATE_CONTENT', outcome: 'SUCCESS', beforeData: { title: '操作前标题', lockVersion: '9007199254740993' }, afterData: { title: '<b>操作后纯文本</b>', fields: ['title', 'description'], nested: { status: 'DRAFT' } }, occurredAt: '2026-10-03T07:00:00.123456Z' };
