import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { mount, flushPromises } from '@vue/test-utils';
import { createPinia } from 'pinia';
import { createMemoryHistory } from 'vue-router';
import App from '../App.vue';
import { createAppRouter } from '../router';
import { api } from '../api/client';
import { business } from '../api/business';
import { useSession } from '../auth/useSession';
import type { AuditResponsePage, RoleCode, SessionResponse } from '../api/contracts.generated';
import { ApiFailure } from '../errors/api-error';
import { syntheticAudit, syntheticComment, syntheticPage, syntheticRequirement, syntheticTag, syntheticUser } from './fixtures';
const id = syntheticRequirement.requirementId;
beforeEach(() => {
  api.clearCsrf(); vi.spyOn(api, 'refreshCsrf').mockResolvedValue(); vi.spyOn(api, 'session').mockResolvedValue({ user: syntheticRequirement.creator, roles: ['REQUIREMENT_ENGINEER'] });
  vi.spyOn(business, 'requirement').mockImplementation(async value => ({ ...syntheticRequirement, requirementId: value })); vi.spyOn(business, 'requirements').mockResolvedValue(syntheticPage([syntheticRequirement])); vi.spyOn(business, 'tags').mockResolvedValue(syntheticPage([syntheticTag])); vi.spyOn(business, 'users').mockResolvedValue(syntheticPage([syntheticUser]));
  vi.spyOn(business, 'history').mockResolvedValue(syntheticPage([syntheticAudit])); vi.spyOn(business, 'auditEvents').mockResolvedValue(syntheticPage([{ ...syntheticAudit, requirementId: null, targetType: 'USER', targetId: 'user:1' }])); vi.spyOn(business, 'comments').mockResolvedValue(syntheticPage([syntheticComment])); vi.spyOn(window, 'confirm').mockReturnValue(true);
});
afterEach(() => vi.restoreAllMocks());
async function workspace(path: string, roles: RoleCode[] = ['REQUIREMENT_ENGINEER']) { vi.mocked(api.session).mockResolvedValue({ user: syntheticRequirement.creator, roles }); const pinia = createPinia(); const router = createAppRouter(pinia, createMemoryHistory()); await router.push(path); await router.isReady(); const wrapper = mount(App, { global: { plugins: [pinia, router] } }); await flushPromises(); return { wrapper, router, pinia }; }
describe('Wave 5 component integration developer checks', () => {
  it.each(['ADMIN', 'REQUIREMENT_ENGINEER', 'REVIEWER', 'PROJECT_MEMBER', 'VIEWER'] as RoleCode[])('renders actual readonly business history for %s with seven stable tabs and escaped safe JSON', async role => {
    const { wrapper } = await workspace(`/requirements/${id}?tab=history`, [role]); expect(business.history).toHaveBeenCalledWith(id, { page: 0, size: 20 }); expect(wrapper.findAll('nav[role=tablist] a[role=tab][data-tab]')).toHaveLength(7); expect(wrapper.find('[data-tab=history]').attributes('aria-selected')).toBe('true'); expect(wrapper.find('b').exists()).toBe(false); expect(wrapper.text()).toContain('<b>操作后纯文本</b>'); expect(wrapper.find('.audit-payload pre').text()).toContain('9007199254740993'); expect(wrapper.text()).toContain('07:00:00.123456 UTC'); expect(wrapper.findAll('.audit-log button').map(button => button.text()).some(label => /删除|修改|创建/.test(label))).toBe(false); wrapper.unmount();
  });
  it('captures only UTC/action filters and rereads without issuing business writes', async () => {
    const { wrapper } = await workspace(`/requirements/${id}?tab=history`, ['VIEWER']); const inputs = wrapper.findAll('.audit-filters input'); await inputs[0]!.setValue('2026-10-03T00:00:00Z'); await inputs[1]!.setValue('2026-10-03T08:00:00Z'); await inputs[2]!.setValue('UPDATE_CONTENT'); await wrapper.find('.audit-filters').trigger('submit'); await flushPromises(); expect(business.history).toHaveBeenLastCalledWith(id, { page: 0, size: 20, from: '2026-10-03T00:00:00Z', to: '2026-10-03T08:00:00Z', action: 'UPDATE_CONTENT' }); wrapper.unmount();
  });
  it('permits system audit only to ADMIN and does not grant business roles', async () => {
    const { wrapper, pinia } = await workspace('/admin/audit', ['ADMIN']); expect(business.auditEvents).toHaveBeenCalledWith({ page: 0, size: 20 }); expect(wrapper.text()).toContain('系统审计'); expect(wrapper.text()).toContain('user:1'); expect(useSession(pinia).hasAnyRole(['REQUIREMENT_ENGINEER', 'REVIEWER', 'PROJECT_MEMBER'])).toBe(false); wrapper.unmount();
    const viewer = await workspace('/admin/audit', ['VIEWER']); expect(viewer.router.currentRoute.value.path).toBe('/forbidden'); expect(business.auditEvents).toHaveBeenCalledTimes(1); viewer.wrapper.unmount();
  });
  it('discards an old history response after switching parent and on session invalidation', async () => {
    let finish!: (value: AuditResponsePage) => void; vi.mocked(business.history).mockImplementationOnce(() => new Promise(resolve => { finish = resolve; })).mockResolvedValue(syntheticPage([{ ...syntheticAudit, requirementId: '2', action: 'SECOND_PARENT' }])); const { wrapper, router, pinia } = await workspace(`/requirements/${id}?tab=history`, ['VIEWER']); await router.push('/requirements/2?tab=history'); await flushPromises(); finish(syntheticPage([syntheticAudit])); await flushPromises(); expect(wrapper.find('.audit-log').text()).toContain('SECOND_PARENT'); expect(wrapper.find('.audit-log').text()).not.toContain('UPDATE_CONTENT'); useSession(pinia).reset(); await flushPromises(); expect(wrapper.find('.audit-log').exists()).toBe(false); wrapper.unmount();
  });
  it('rechecks roles before draft writes and sends nothing after an unmounted role lookup', async () => {
    const send = vi.spyOn(business, 'editContent'); const { wrapper, router } = await workspace(`/requirements/${id}/edit`); vi.mocked(api.session).mockResolvedValue({ user: syntheticRequirement.creator, roles: ['VIEWER'] }); await wrapper.find('form').trigger('submit'); await flushPromises(); expect(send).not.toHaveBeenCalled(); expect(wrapper.find('form').exists()).toBe(false); wrapper.unmount();
    const view = await workspace(`/requirements/${id}/edit`); let finish!: (value: SessionResponse) => void; vi.mocked(api.session).mockImplementationOnce(() => new Promise(resolve => { finish = resolve; })); await view.wrapper.find('form').trigger('submit'); await flushPromises(); await view.router.push('/requirements'); await flushPromises(); finish({ user: syntheticRequirement.creator, roles: ['REQUIREMENT_ENGINEER'] }); await flushPromises(); expect(send).not.toHaveBeenCalled(); view.wrapper.unmount(); void router;
  });
  it('integrates current comment controls with plain-text create and author-only logical delete responses', async () => {
    const send = vi.spyOn(business, 'createComment').mockResolvedValue({ ...syntheticComment, content: '<script>纯文本自检</script>' }); const remove = vi.spyOn(business, 'deleteComment').mockResolvedValue(); const { wrapper } = await workspace(`/requirements/${id}?tab=comments`, ['PROJECT_MEMBER']); await wrapper.find('textarea[placeholder="输入纯文本评论"]').setValue('<script>纯文本自检</script>'); await wrapper.find('form').trigger('submit'); await flushPromises(); expect(send).toHaveBeenCalledWith(id, { content: '<script>纯文本自检</script>' }); expect((wrapper.find('textarea').element as HTMLTextAreaElement).value).toBe(''); vi.mocked(business.comments).mockResolvedValue(syntheticPage([{ ...syntheticComment, isDeleted: 1, content: null, deletedBy: '1', deletedAt: '2026-10-03T08:00:00Z' }])); await wrapper.findAll('button').find(button => button.text() === '删除本人评论')!.trigger('click'); await flushPromises(); expect(window.confirm).toHaveBeenCalledWith('确认逻辑删除本人的这条评论？'); expect(remove).toHaveBeenCalledWith(syntheticComment.commentId); expect(wrapper.text()).toContain('此评论已删除'); expect(wrapper.text()).not.toContain('删除本人评论'); wrapper.unmount();
  });
  it('blocks tag conflict replay through form clearing until explicit catalog reread', async () => {
    const send = vi.spyOn(business, 'createTag').mockRejectedValue(new ApiFailure('INTERNAL_ERROR', 'server', 500, undefined, undefined, true)); const { wrapper } = await workspace(`/requirements/${id}`); await wrapper.find('.tag-catalog form:last-child input').setValue('保留标签'); await wrapper.find('.tag-catalog form:last-child').trigger('submit'); await flushPromises(); expect(wrapper.findAll('.tag-catalog button').find(button => button.text() === '清空表单')!.attributes('disabled')).toBeDefined(); await wrapper.find('.tag-catalog form:last-child').trigger('submit'); await flushPromises(); expect(send).toHaveBeenCalledTimes(1); expect((wrapper.find('.tag-catalog form:last-child input').element as HTMLInputElement).value).toBe('保留标签'); await wrapper.find('.tag-catalog .error-panel button').trigger('click'); await flushPromises(); expect(send).toHaveBeenCalledTimes(1); wrapper.unmount();
  });
  it('discards a completed metadata response if an explicit parent reread has already adopted a different revision', async () => {
    let finish!: (value: typeof syntheticRequirement) => void; vi.spyOn(business, 'editMetadata').mockImplementationOnce(() => new Promise(resolve => { finish = resolve; })); const { wrapper } = await workspace(`/requirements/${id}`); await wrapper.find('input[placeholder="已知且启用的用户 ID，留空清除"]').setValue('2'); await wrapper.find('form').trigger('submit'); await flushPromises(); vi.mocked(business.requirement).mockResolvedValueOnce({ ...syntheticRequirement, lockVersion: '9007199254740996', assigneeId: '3', assignee: { userId: '3', displayName: '最新负责人', accountStatus: 'ENABLED' } }); await wrapper.findAll('button').find(button => button.text() === '重新读取需求')!.trigger('click'); await flushPromises(); finish({ ...syntheticRequirement, lockVersion: '9007199254740994', assigneeId: '2', assignee: { userId: '2', displayName: '旧结果负责人', accountStatus: 'ENABLED' } }); await flushPromises(); expect(wrapper.text()).toContain('最新负责人'); expect(wrapper.text()).toContain('9007199254740996'); expect(wrapper.text()).not.toContain('旧结果负责人'); wrapper.unmount();
  });
});
