import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { mount, flushPromises } from '@vue/test-utils';
import { createPinia } from 'pinia';
import { createMemoryHistory } from 'vue-router';
import App from '../App.vue';
import { createAppRouter } from '../router';
import { api } from '../api/client';
import { business } from '../api/business';
import { ApiFailure } from '../errors/api-error';
import type { RequirementRelationResponse, RequirementResponse, RoleCode, TraceResponse } from '../api/contracts.generated';
import { syntheticComment, syntheticOther, syntheticPage, syntheticRelation, syntheticRequirement, syntheticTrace, syntheticTag } from './fixtures';
const parentId = syntheticRequirement.requirementId; const path = `/requirements/${parentId}?tab=relations`; const canonical: RequirementRelationResponse = { ...syntheticRelation, sourceRequirementId: syntheticOther.requirementId, targetRequirementId: parentId, relationType: 'RELATES_TO' };
beforeEach(() => {
  api.clearCsrf(); vi.spyOn(api, 'refreshCsrf').mockResolvedValue(); vi.spyOn(api, 'session').mockResolvedValue({ user: syntheticRequirement.creator, roles: ['REQUIREMENT_ENGINEER'] });
  vi.spyOn(business, 'requirement').mockImplementation(async id => id === syntheticOther.requirementId ? syntheticOther : { ...syntheticRequirement, requirementId: id }); vi.spyOn(business, 'relations').mockResolvedValue(syntheticPage([syntheticRelation])); vi.spyOn(business, 'trace').mockResolvedValue(syntheticTrace); vi.spyOn(business, 'tags').mockResolvedValue(syntheticPage([syntheticTag])); vi.spyOn(business, 'history').mockResolvedValue(syntheticPage([]));
  vi.spyOn(business, 'comments').mockResolvedValue(syntheticPage([syntheticComment])); vi.spyOn(window, 'confirm').mockReturnValue(true);
});
afterEach(() => vi.restoreAllMocks());
async function workspace(url: string, roles: RoleCode[] = ['REQUIREMENT_ENGINEER']) {
  vi.mocked(api.session).mockResolvedValue({ user: syntheticRequirement.creator, roles }); const pinia = createPinia(); const router = createAppRouter(pinia, createMemoryHistory()); await router.push(url); await router.isReady(); const wrapper = mount(App, { global: { plugins: [pinia, router] } }); await flushPromises(); return { wrapper, router };
}
async function selectOther(wrapper: ReturnType<typeof mount>) { await wrapper.find('.relation-create input').setValue(syntheticOther.requirementId); await wrapper.findAll('.relation-create button').find(item => item.text() === '读取并核对对端需求')!.trigger('click'); await flushPromises(); }
describe('Wave 4 relation/trace/withdraw component developer checks', () => {
  it('reads direct relations and trace only after parent, preserving source/type/target and safe plaintext', async () => {
    vi.mocked(business.relations).mockResolvedValue(syntheticPage([{ ...syntheticRelation, description: '<b>纯文本关系</b>' }])); const { wrapper } = await workspace(path, ['VIEWER']); expect(business.relations).toHaveBeenCalledWith(parentId, { page: 0, size: 20 }); expect(business.trace).toHaveBeenCalledWith(parentId, { depth: 2 }); expect(wrapper.text()).toContain('DEPENDS_ON'); expect(wrapper.text()).toContain('出向'); expect(wrapper.text()).toContain('<b>纯文本关系</b>'); expect(wrapper.find('b').exists()).toBe(false); expect(wrapper.find('.relation-create').exists()).toBe(false); expect(wrapper.text()).not.toContain('核对两端后解除'); wrapper.unmount();
  });
  it('creates outgoing directed relation from read parent/counterpart revisions', async () => {
    const send = vi.spyOn(business, 'createRelation').mockResolvedValue(syntheticRelation); const { wrapper } = await workspace(path); await selectOther(wrapper); await wrapper.find('.relation-create textarea').setValue('依赖说明'); await wrapper.find('.relation-create').trigger('submit'); await flushPromises(); expect(send).toHaveBeenCalledWith({ sourceRequirementId: parentId, targetRequirementId: '2', relationType: 'DEPENDS_ON', description: '依赖说明', expectedSourceLockVersion: syntheticRequirement.lockVersion, expectedTargetLockVersion: '8' }); expect(wrapper.text()).toContain('已建立 DEPENDS_ON'); expect(business.trace).toHaveBeenCalledTimes(2); wrapper.unmount();
  });
  it('creates incoming relation without reversing either endpoint revision', async () => {
    const send = vi.spyOn(business, 'createRelation').mockResolvedValue({ ...syntheticRelation, sourceRequirementId: '2', targetRequirementId: parentId }); const { wrapper } = await workspace(path); await selectOther(wrapper); await wrapper.findAll('.relation-create select')[1]!.setValue('true'); await wrapper.find('.relation-create').trigger('submit'); await flushPromises(); expect(send).toHaveBeenCalledWith({ sourceRequirementId: '2', targetRequirementId: parentId, relationType: 'DEPENDS_ON', description: null, expectedSourceLockVersion: '8', expectedTargetLockVersion: syntheticRequirement.lockVersion }); wrapper.unmount();
  });
  it('displays server normalized symmetric roles and deletes with fresh revisions mapped to returned endpoints', async () => {
    vi.mocked(business.relations).mockResolvedValue(syntheticPage([canonical])); const send = vi.spyOn(business, 'createRelation').mockResolvedValue(canonical); const remove = vi.spyOn(business, 'deleteRelation').mockResolvedValue(); const { wrapper } = await workspace(path); await selectOther(wrapper); await wrapper.findAll('.relation-create select')[0]!.setValue('RELATES_TO'); await wrapper.find('.relation-create').trigger('submit'); await flushPromises(); expect(send).toHaveBeenCalledWith(expect.objectContaining({ sourceRequirementId: parentId, expectedSourceLockVersion: syntheticRequirement.lockVersion, targetRequirementId: '2', expectedTargetLockVersion: '8' })); expect(wrapper.text()).toContain('对称'); expect(wrapper.text()).toContain(`已建立 RELATES_TO：2 ↔ ${parentId}`);
    await wrapper.findAll('.relation-panel table button')[0]!.trigger('click'); await flushPromises(); expect(wrapper.find('.relation-delete').text()).toContain('返回的源需求 2 · 修订 8'); expect(wrapper.find('.relation-delete').text()).toContain(`返回的目标需求 ${parentId} · 修订 ${syntheticRequirement.lockVersion}`); await wrapper.findAll('.relation-delete button').find(item => item.text() === '确认解除关系')!.trigger('click'); await flushPromises(); expect(remove).toHaveBeenCalledWith(canonical.relationId, { expectedSourceLockVersion: '8', expectedTargetLockVersion: syntheticRequirement.lockVersion }); wrapper.unmount();
  });
  it('requires valid non-self/non-withdrawn counterpart and hides graph writes for withdrawn parent or ADMIN-only', async () => {
    const send = vi.spyOn(business, 'createRelation'); const { wrapper } = await workspace(path); const reads = vi.mocked(business.requirement).mock.calls.length; await wrapper.find('.relation-create input').setValue(parentId); await wrapper.findAll('.relation-create button')[0]!.trigger('click'); await flushPromises(); expect(business.requirement).toHaveBeenCalledTimes(reads); expect(send).not.toHaveBeenCalled();
    vi.mocked(business.requirement).mockImplementation(async id => id === '2' ? { ...syntheticOther, isWithdrawn: 1 } : syntheticRequirement); await selectOther(wrapper); expect(wrapper.text()).toContain('已撤销，不可写'); expect(wrapper.findAll('.relation-create button').at(-1)!.attributes('disabled')).toBeDefined(); wrapper.unmount();
    vi.mocked(business.requirement).mockResolvedValue({ ...syntheticRequirement, isWithdrawn: 1 }); const withdrawn = await workspace(path); expect(withdrawn.wrapper.find('.relation-create').exists()).toBe(false); expect(withdrawn.wrapper.text()).not.toContain('核对两端后解除'); withdrawn.wrapper.unmount(); vi.mocked(business.requirement).mockResolvedValue(syntheticRequirement); const admin = await workspace(path, ['ADMIN']); expect(admin.wrapper.find('.relation-create').exists()).toBe(false); admin.wrapper.unmount();
  });
  it.each(['DEPENDENCY_CYCLE', 'DUPLICATE', 'GRAPH_BUSY'] as const)('preserves graph draft after %s409 until explicit endpoint rereads', async code => {
    const send = vi.spyOn(business, 'createRelation').mockRejectedValue(new ApiFailure(code, 'conflict', 409)); const { wrapper } = await workspace(path); await selectOther(wrapper); await wrapper.find('.relation-create textarea').setValue('保留关系说明'); await wrapper.find('.relation-create').trigger('submit'); await flushPromises(); expect(wrapper.text()).toContain('本地表单保留'); expect(send).toHaveBeenCalledTimes(1);
    vi.mocked(business.requirement).mockImplementation(async id => id === '2' ? { ...syntheticOther, lockVersion: '9' } : { ...syntheticRequirement, lockVersion: '9007199254740994' }); await wrapper.find('.error-panel button').trigger('click'); await flushPromises(); expect((wrapper.find('.relation-create textarea').element as HTMLTextAreaElement).value).toBe('保留关系说明'); expect((wrapper.find('.relation-create input').element as HTMLInputElement).value).toBe('2'); expect(send).toHaveBeenCalledTimes(1); await wrapper.find('.relation-create').trigger('submit'); await flushPromises(); expect(send).toHaveBeenLastCalledWith(expect.objectContaining({ expectedSourceLockVersion: '9007199254740994', expectedTargetLockVersion: '9', description: '保留关系说明' })); wrapper.unmount();
  });
  it('blocks unknown create replay and requires actual refreshed reads without retry', async () => {
    const send = vi.spyOn(business, 'createRelation').mockRejectedValue(new ApiFailure('INTERNAL_ERROR', 'server', 500, undefined, undefined, true)); const { wrapper } = await workspace(path); await selectOther(wrapper); await wrapper.find('.relation-create textarea').setValue('未知结果说明'); await wrapper.find('.relation-create').trigger('submit'); await flushPromises(); await wrapper.find('.relation-create').trigger('submit'); await flushPromises(); expect(send).toHaveBeenCalledTimes(1); await wrapper.find('.error-panel button').trigger('click'); await flushPromises(); expect(send).toHaveBeenCalledTimes(1); expect((wrapper.find('.relation-create textarea').element as HTMLTextAreaElement).value).toBe('未知结果说明'); wrapper.unmount();
  });
  it('reconciles delete conflict with new normalized source and target revisions', async () => {
    vi.mocked(business.relations).mockResolvedValue(syntheticPage([canonical])); const send = vi.spyOn(business, 'deleteRelation').mockRejectedValueOnce(new ApiFailure('LOCK_VERSION_CONFLICT', 'conflict', 409)).mockResolvedValueOnce(); const { wrapper } = await workspace(path); await wrapper.findAll('.relation-panel table button')[0]!.trigger('click'); await flushPromises(); await wrapper.findAll('.relation-delete button')[0]!.trigger('click'); await flushPromises();
    vi.mocked(business.requirement).mockImplementation(async id => id === '2' ? { ...syntheticOther, lockVersion: '9' } : { ...syntheticRequirement, lockVersion: '9007199254740994' }); await wrapper.find('.error-panel button').trigger('click'); await flushPromises(); expect(send).toHaveBeenCalledTimes(1); await wrapper.findAll('.relation-delete button')[0]!.trigger('click'); await flushPromises(); expect(send).toHaveBeenLastCalledWith(canonical.relationId, { expectedSourceLockVersion: '9', expectedTargetLockVersion: '9007199254740994' }); wrapper.unmount();
  });
  it('deduplicates typed trace nodes/edges without recursive reads and shows depth/type/truncation', async () => {
    vi.mocked(business.trace).mockResolvedValue({ ...syntheticTrace, nodes: [...syntheticTrace.nodes, syntheticOther], edges: [syntheticRelation, syntheticRelation], truncated: true }); const { wrapper } = await workspace(path, ['VIEWER']); expect(wrapper.text()).toContain('2 个节点 · 1 条关系'); expect(wrapper.findAll('.trace-nodes li')).toHaveLength(2); expect(wrapper.text()).toContain('结果已截断'); expect(business.requirement).toHaveBeenCalledTimes(1);
    await wrapper.find('.trace-filters input').setValue('3'); await wrapper.find('.trace-filters select').setValue('DEPENDS_ON'); vi.mocked(business.trace).mockResolvedValue({ ...syntheticTrace, depth: 3 }); await wrapper.find('.trace-filters').trigger('submit'); await flushPromises(); expect(business.trace).toHaveBeenLastCalledWith(parentId, { depth: 3, relationType: 'DEPENDS_ON' }); expect(wrapper.text()).toContain('深度 3'); wrapper.unmount();
  });
  it('uses fresh actual role checks before graph mutation and discards late graph reads on navigation', async () => {
    const send = vi.spyOn(business, 'createRelation'); const { wrapper } = await workspace(path); await selectOther(wrapper); vi.mocked(api.session).mockResolvedValue({ user: syntheticRequirement.creator, roles: ['VIEWER'] }); await wrapper.find('.relation-create').trigger('submit'); await flushPromises(); expect(send).not.toHaveBeenCalled(); expect(wrapper.find('.relation-create').exists()).toBe(false); wrapper.unmount();
    let finish!: (value: TraceResponse) => void; vi.mocked(business.trace).mockImplementationOnce(() => new Promise(resolve => { finish = resolve; })).mockResolvedValue({ ...syntheticTrace, rootRequirementId: '2' }); const view = await workspace(path, ['VIEWER']); await view.router.push('/requirements/2?tab=relations'); await flushPromises(); finish(syntheticTrace); await flushPromises(); expect(view.wrapper.find('.trace-graph').text()).toContain('根需求 2 · 深度'); expect(view.wrapper.find('.trace-graph').text()).not.toContain(`根需求 ${parentId} · 深度`); view.wrapper.unmount();
  });
  it('checks fresh never-submitted draft and empty relations before explicit logical withdrawal', async () => {
    vi.mocked(business.relations).mockResolvedValue(syntheticPage([], 1)); const withdrawn: RequirementResponse = { ...syntheticRequirement, isWithdrawn: 1, withdrawnBy: '1', withdrawnAt: '2026-10-03T07:00:00Z', lockVersion: '9007199254740994' }; const send = vi.spyOn(business, 'withdrawRequirement').mockResolvedValue(withdrawn); const { wrapper } = await workspace(`/requirements/${parentId}`);
    expect(wrapper.text()).not.toContain('确认逻辑撤销草稿'); await wrapper.find('.withdraw-action button').trigger('click'); await flushPromises(); expect(business.relations).toHaveBeenCalledWith(parentId, { page: 0, size: 1 }); await wrapper.findAll('.withdraw-action button').find(item => item.text() === '确认逻辑撤销草稿')!.trigger('click'); await flushPromises(); expect(send).toHaveBeenCalledWith(parentId, { expectedLockVersion: syntheticRequirement.lockVersion }); expect(wrapper.text()).toContain('已撤销 · 只读'); expect(wrapper.text()).toContain('原记录、版本、评审、评论与变更历史保留只读'); expect(wrapper.find('form').exists()).toBe(false); expect(wrapper.text()).not.toContain('编辑草稿'); wrapper.unmount();
  });
  it('prevents withdrawal with effective relations or prior first submission even after return to DRAFT', async () => {
    const send = vi.spyOn(business, 'withdrawRequirement'); const { wrapper } = await workspace(`/requirements/${parentId}`); await wrapper.find('.withdraw-action button').trigger('click'); await flushPromises(); expect(wrapper.text()).toContain('请先解除有效关联'); expect(wrapper.text()).not.toContain('确认逻辑撤销草稿'); expect(send).not.toHaveBeenCalled(); wrapper.unmount();
    vi.mocked(business.requirement).mockResolvedValue({ ...syntheticRequirement, firstSubmittedAt: '2026-10-03T01:00:00Z' }); const submitted = await workspace(`/requirements/${parentId}`); expect(submitted.wrapper.find('.withdraw-action button').exists()).toBe(false); expect(submitted.wrapper.text()).toContain('退回或重新打开的草稿也不能撤销'); submitted.wrapper.unmount();
  });
  it('reconciles unknown withdrawal by read and does not repeat an already completed mutation', async () => {
    vi.mocked(business.relations).mockResolvedValue(syntheticPage([], 1)); const send = vi.spyOn(business, 'withdrawRequirement').mockRejectedValue(new ApiFailure('INTERNAL_ERROR', 'server', 500, undefined, undefined, true)); const { wrapper } = await workspace(`/requirements/${parentId}`); await wrapper.find('.withdraw-action button').trigger('click'); await flushPromises(); await wrapper.findAll('.withdraw-action button').find(item => item.text() === '确认逻辑撤销草稿')!.trigger('click'); await flushPromises(); expect(send).toHaveBeenCalledTimes(1);
    vi.mocked(business.requirement).mockResolvedValue({ ...syntheticRequirement, isWithdrawn: 1, withdrawnBy: '1', withdrawnAt: '2026-10-03T07:00:00Z' }); await wrapper.find('.withdraw-action .error-panel button').trigger('click'); await flushPromises(); expect(send).toHaveBeenCalledTimes(1); expect(wrapper.find('.withdraw-action button').exists()).toBe(false); expect(wrapper.text()).toContain('已撤销 · 只读'); wrapper.unmount();
  });
  it('keeps withdrawn editor/comments/relations readonly and keeps business history readonly', async () => {
    vi.mocked(business.requirement).mockResolvedValue({ ...syntheticRequirement, isWithdrawn: 1, withdrawnBy: '1', withdrawnAt: '2026-10-03T07:00:00Z' }); const editor = await workspace(`/requirements/${parentId}/edit`); expect(editor.wrapper.find('form').exists()).toBe(false); expect(editor.wrapper.text()).toContain('普通纯文本'); editor.wrapper.unmount();
    const { wrapper, router } = await workspace(`/requirements/${parentId}?tab=comments`); expect(wrapper.text()).toContain(syntheticComment.content!); expect(wrapper.find('form').exists()).toBe(false); expect(wrapper.text()).not.toContain('删除本人评论'); await router.push(path); await flushPromises(); expect(wrapper.find('.relation-create').exists()).toBe(false); expect(wrapper.text()).not.toContain('核对两端后解除'); const traces = vi.mocked(business.trace).mock.calls.length; await router.push(`/requirements/${parentId}?tab=history`); await flushPromises(); expect(wrapper.text()).toContain('需求业务历史'); expect(business.history).toHaveBeenCalledWith(syntheticRequirement.requirementId, { page: 0, size: 20 }); expect(business.trace).toHaveBeenCalledTimes(traces); wrapper.unmount();
  });
});
